### ISSUE TITLE
TypeError: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by benoittgt** [awslabs/amazon-redshift-utils#103]
Hello

First thanks for the tools. I get an error when using `analyze-schema-compression`
```
Traceback (most recent call last):
  File "./analyze-schema-compression.py", line 1004, in <module>
    main(sys.argv)
  File "./analyze-schema-compression.py", line 995, in main
    configure(output_file, db, db_user, db_pwd, db_host, db_port, analyze_schema, target_schema, analyze_table, threads, do_execute, query_slot_count, ignore_errors, force, drop_old_data, comprows, query_group, debug, ssl_option)
  File "./analyze-schema-compression.py", line 691, in configure
    comprows = None if _comprows == -1 else int(_comprows)
TypeError: int() argument must be a string or a number, not 'NoneType'
```

I remove the if statement for `comprows` and `query_slot_count` and set my value to avoid the problem.

Cheers

**Comment by kicks66** [comment]
Im getting the same issue, is there a solution other than manually coding the values? And what are those values meant to represent (`comprows` and `query_slot_count`)

**Comment by IanMeyers** [comment]
can you supply the command line syntax you are using when you see the error?

Thx!

**Comment by kicks66** [comment]
`python analyze-schema-compression.py --db xxx --db-user yyy --db-host zzz.eu-west-1.redshift.amazonaws.com --db-port 5439 --analyze-schema aaa --output-file "test.txt"`

**Comment by IanMeyers** [comment]
This is fixed in https://github.com/awslabs/amazon-redshift-utils/commit/4fdd5eadeca12518661ee1ab6570ab78004052f4. Do let me know if you have any other issues.

**Comment by benoittgt** [comment]
Thanks a lot @IanMeyers
