### ISSUE TITLE
Perf improvement opportunity long running transactions for ColumnEncodingUtility

### ISSUE THREAD

**Issue by zach-data** [awslabs/amazon-redshift-utils#106]
ANALYZE COMPRESSION requires an exclusive lock to begin, which is held through the duration of the transaction once granted - blocking reads.

It would be better to implement this in a way such that the analyze compression per table is performed in a single transaction (including rebuild if enabled). This approach would reduce lock contention.

**Comment by IanMeyers** [comment]
Agreed - will look to move the table lock to just enclose the table rename operations.

**Comment by IanMeyers** [comment]
But. Thinking back, there was a feature request made the a customer needed 100% transactional consistency across the optimisation, which requires an exclusive write lock. Barring the ability to issue a lock table statement that only blocks writes, I don't see any way to address both needs other than issuing a very complex to build update statement of some sort. Thoughts?
