### ISSUE TITLE
table_info.sql return ERROR:  Numeric data overflow (result precision)

### ISSUE THREAD

**Issue by patanachai** [awslabs/amazon-redshift-utils#114]
Here is the full exception

psql:table_info.sql:49: ERROR:  Numeric data overflow (result precision)
DETAIL:  

---

  error:  Numeric data overflow (result precision)
  code:      1058
  context:   64 bit overflow
  query:     982615
  location:  numeric.hpp:161
  process:   query0_68 [pid=17689]

---

**Comment by rafiton** [comment]
Getting the same error:

```
ERROR:  Numeric data overflow (result precision)
DETAIL:  
  -----------------------------------------------
  error:  Numeric data overflow (result precision)
  code:      1058
  context:   64 bit overflow
  query:     4327893
  location:  numeric.hpp:161
  process:   query30_52 [pid=21323]
  -----------------------------------------------
```

**Comment by saeedma8** [comment]
Increased the size of the decimal fields to prevent Numeric data overflow. Please let us know if the issue still persists. Thank you.
