### ISSUE TITLE
Vacuum delete only 

### ISSUE THREAD

**Issue by Jaskirat** [awslabs/amazon-redshift-utils#115]
The column encoding utility doesn't really run "vacuum delete only" when run with a --do-execute=True but writes it to the generated sql script. 

1. I don't understand why a vacuum delete is really needed since the script doesn't seem to do any update/delete operations
2. If it is indeed needed then why one behavior when do-execute is true and another behavior when false?

--
Link - https://github.com/awslabs/amazon-redshift-utils/blob/master/src/ColumnEncodingUtility/analyze-schema-compression.py#L825

**Comment by IanMeyers** [comment]
Thanks for spotting this. It's now fixed in https://github.com/awslabs/amazon-redshift-utils/commit/eb0d4357df5e0cc1121d9baa2bc58faa73d3353b.

**Comment by Jaskirat** [comment]
I am not sure how you tested this but when I do run the script that is generated like below

    begin;
    lock ...
    ...
    commit;
    
    vacuum delete only;

I am simply running each statement using a pg8000's connection.cursor() and cursor.execute(statement) i get an error like below

    ProgrammingError: (u'ERROR', u'25001', u'VACUUM cannot run inside a transaction block', u'/home/rdsdb/padb/src/pg/src/backend/access/transam/xact.c', u'2541', u'PreventTransactionChain', u'', u'')

I am not sure how the utility would avoid this error.

**Comment by Jaskirat** [comment]
Also is the vacuum really needed if no update/delete operations are actually performed by this script? It only seems to insert/drop tables.

**Comment by IanMeyers** [comment]
I will look into the transaction issue you are reporting and get back to you. You can safely remove the VACUUM DELETE, especially if you have VACUUM processes running at some other time.

**Comment by IanMeyers** [comment]
So yes - have clarified that this vacuum is not required. Will remove in a subsequent patch.

**Comment by Jaskirat** [comment]
Great. Thanks!

**Comment by IanMeyers** [comment]
Fixed on https://github.com/awslabs/amazon-redshift-utils/commit/9424b6d9f4cb68cca4209db7db4676f72368c2ab
