### ISSUE TITLE
AnalyzeVacuumUtility password management

### ISSUE THREAD

**Issue by kenfar** [awslabs/amazon-redshift-utils#122]
Currently this utility requires the password to be provided as an argument.

This means that the userid & password are vulnerable and can be picked up by anyone on the system and watching for processes, or they may be picked up by any endpoint security software and then kept in logs where others can then access them.  Beyond making the systems that use this utility vulnerable to attack, it would also be a security policy violation in many locations.

I'd like to propose supporting either a .pgpass file or environmental variables for storing this password, ideally both.  The python library pgpasslib (https://pgpasslib.readthedocs.io/en/latest/) is a simple module to assist in reading from the .pgpass file.

**Comment by raam86** [comment]
Any progress on this?

**Comment by IanMeyers** [comment]
This should now work from https://github.com/awslabs/amazon-redshift-utils/commit/d2d18347c45f42e1ec4685acfc2fd71541222247 for the analyze/vacuum and column encoding utilities. More to come.

**Comment by timjell** [comment]
Closing as fixed per IanMeyers comment above
