### ISSUE TITLE
analyze-vacuum-schema.py not working 

### ISSUE THREAD

**Issue by pankajagarwal** [awslabs/amazon-redshift-utils#126]
analyze-vacuum-schema.py is not detecting any tables to vaccum and analyze. Sample output for reference is provided here ... "Query Execution returned 0 Results" 

while the queries in the above python script returns 0 values, if i run the following sql it fetches me atleast 10-15 tables ...

select * from SVV_TABLE_INFO where unsorted > 10

**Comment by raam86** [comment]
make sure the target schema you selected exists in your database
