### ISSUE TITLE
v_space_used_per_tbl gives divide by zero error when encountering table with zero records

### ISSUE THREAD

**Issue by tinkerbotfoo** [awslabs/amazon-redshift-utils#13]
These lines cause the error. Need to handle scenarios where tables can be empty.	

	,ROUND((a.unsorted_rows::FLOAT / a.rows::FLOAT) * 100, 5) AS pct_unsorted
		,CASE WHEN (a.unsorted_rows::FLOAT / a.rows::FLOAT) * 100 >= 20 
			THEN 'VACUUM recommended' ELSE 'n/a' END AS recommendation

Note: Thanks for publishing these utilities. I have been putting together a similar one but you have done it several times better

**Comment by tinkerbotfoo** [comment]
It is a simple fix. I have submitted a pull request. please review.

**Comment by IanMeyers** [comment]
Fixed in pull request 14
