### ISSUE TITLE
AnalyzeVacuumUtility produces missing shared library GLFW3 error running in Windows cmd

### ISSUE THREAD

**Issue by jefflehmann** [awslabs/amazon-redshift-utils#132]
C:\Users\mc55168\Documents\Redshift\Analyze - Vacuum Utility>python analyze-vacuum-schema.py  --db xxxxxdb --db-user admin --db-port 5439 --db-host us-east-xxxxx-us-cds-cpd1-redshift-xxxxxxxxxxxxxxx-xxxxx.xxxxxxxxxx.us-east-1.redshift.amazonaws.com --schema-name prod_tables  --table-name cust_xxxx_xxxx_vers --output-file xxxxxxx_analyze_vacuum_cust_xxxx_xxxx_vers.log --debug True --ignore-errors False --slot-count 5 --vacuum-flag True --vacuum-parameter FULL --analyze-flag True --min-unsorted-pct 5 --max-unsorted-pct 50 --deleted-pct 15 --stats-off-pct 10 --max-table-size-mb 272417
Traceback (most recent call last):
  File "analyze-vacuum-schema.py", line 44, in <module>
    import pg
  File "C:\python27\lib\site-packages\pg\__init__.py", line 1, in <module>
    from .core import (
  File "C:\python27\lib\site-packages\pg\core.py", line 6, in <module>
    from . import glfw
  File "C:\python27\lib\site-packages\pg\glfw.py", line 140, in <module>
    raise ImportError("Failed to load GLFW3 shared library.")
ImportError: Failed to load GLFW3 shared library.

**Comment by timjell** [comment]
Closing as outdated, all apps migrated to Python 3
