### ISSUE TITLE
Admin Views :- Create or Replace View failing

### ISSUE THREAD

**Issue by sadhasivam** [awslabs/amazon-redshift-utils#134]
Minor issue master commit #54cc0fa77038e74303d1627a931d867bbe9a5bba

Following views are breaking: we have to explicitly drop them because Data Type is changing. 

- v_open_session.sql
- v_extended_table_info.sql
- v_space_used_per_tbl.sql

![image](https://cloud.githubusercontent.com/assets/253447/20990821/f1584ff0-bca8-11e6-8318-bc966ed36e28.png)

**Comment by zach-data** [comment]
This is known limitation of the Redshift engine. We try to avoid changing data types, but we will update views in this way from time to time - so this may occur. When it does the DROP & CREATE approach is recommended.

**Comment by ijoel92** [comment]
What if the drop has dependencies? (let's say MANY) dependencies. Is there a way to avoid DROP & CREATE ?
