### ISSUE TITLE
Convert repository to python package

### ISSUE THREAD

**Issue by eyaltrabelsi** [awslabs/amazon-redshift-utils#135]
First of all great work on this repo , it make redshift admin's work a easier .
Could be cool tough to change this repository tol be python package , which will allow for better programmatic experience .

**Comment by IanMeyers** [comment]
Indeed - very open to a Pull Request to do this. Do you want this for all tools or for one specifically?

**Comment by eyaltrabelsi** [comment]
My current need is specifically the AnalyzeVacuumUtility sub-directory but i personally think it will be beneficial to convert the entire repo

**Comment by jbasko** [comment]
@IanMeyers I have a similar need -- a Python package that would allow to build on the goodies from this amazing repo. Has anything changed since 2016 and is there now an alternative to the idea?

**Comment by IanMeyers** [comment]
If you look at the RedshiftAutomation project, you can see how much of this project is used as a package. Does that work for you?

**Comment by jbasko** [comment]
Thanks, but no. For now I just need to use some of the AdminViews definitions and due to my deployment setup it's easier to include a python package than to git clone or copy files from github.

**Comment by timjell** [comment]
Closing this issue as no longer relevant
