### ISSUE TITLE
Can We use the UnloadCopyUtlity to migrate data between two redshift clusters, between two different accounts. 

### ISSUE THREAD

**Issue by athakral** [awslabs/amazon-redshift-utils#137]
We have an EC2 Instance that has vpc peering configured and it is connected to a different users's vpc. So, it is able to connect to the redshift cluster of the different user. Can we run this UnloadCopyUtility to migrate data in between different users's redshift cluster to our redshift cluster. 

(Our redshift cluster is accessible over public ip, in future we might add one more n/w interface and assign that to our subnet and make sure that it can connect to our redshift cluster over private ip as well). 

https://github.com/awslabs/amazon-redshift-utils/tree/master/src/UnloadCopyUtility

**Comment by IanMeyers** [comment]
Yes, this should work fine, provided that each cluster can read from the S3 bucket which you use to exchange data.
