### ISSUE TITLE
Compression Utility - Table name started by a number

### ISSUE THREAD

**Issue by MarioSalgado** [awslabs/amazon-redshift-utils#142]
Hi guys,

I'm sorry but i can't run the compression utility on tables that the name starts with a number, for example '8ball...'.

I'm getting this error:

(u'ERROR', u'42601', u'syntax error at or near ".8"', u'27', u'/home/ec2-user/padb/src/pg/src/backend/parser/parser_scan.l', u'699', u'yyerror', u'', u'')

Is there any way this can be quick fixed?

Thanks a lot

**Comment by IanMeyers** [comment]
This should work fine if for each table that starts with a number, you issue a command which includes "—analyze-table <my numeric tablename>". Can you please verify this? In the meantime I'll be looking to see if there's a reason we specifically exclude tables such as this. Generally speaking this is a bad idea in that there will be databases that fully don't support number leading chars, and also will require that all SQL double quote the table name, which isn't very user friendly.

Thx,

Ian

**Comment by MarioSalgado** [comment]
Hey Ian,

Thank you for your time and help.

I'm sorry but if i run: "—analyze-table 8ball..." It also fails.

I understand your point but renaming these tables at the moment is not possible for us.

**Comment by MarioSalgado** [comment]
Any news regarding this @IanMeyers ?

**Comment by IanMeyers** [comment]
As far as I can tell, this is fixed in version .9.2.5. There were a few outstanding issues with table double quoting which are fixed now.

```
meyersi$ python analyze-schema-compression.py --db master --db-user master --db-host localhost --db-port 5439 --analyze-table 8ball --output-file /Users/meyersi/Temp/8ball.sql --force true
Password <master>:
-- [17348] Connected to localhost:5439:master as master
-- [17348] Analyzing Table '8ball' for Columnar Encoding Optimisations with 1 Threads...
-- [17348] Analyzing 1 table(s) which contain allocated data blocks
-- [17348] Table 8ball contains 1 unoptimised columns
-- [17348] Using Force Override Option
-- [17348] Analyzing Table '8ball'
-- [17348] Column Encoding will be modified for public.8ball
-- [17348] No encoding modifications required for public.8ball
begin;
lock table public."8ball";
create table public."8ball_$mig"(
"columna" varchar(100)   encode raw
)
;
insert into public."8ball_$mig"  select * from public."8ball";
analyze public."8ball_$mig";
alter table public."8ball" rename to "8ball_20170208_BAeD9mq6ro_$old";
alter table public."8ball_$mig" rename to "8ball";
commit;
-- [17348] Performed modification of 0 tables
-- [17348] Processing Complete
```

**Comment by MarioSalgado** [comment]
Hi @IanMeyers i confirm that is working.

Thanks alot for the help!
