### ISSUE TITLE
RedShift UDF to access S3 resource

### ISSUE THREAD

**Issue by BardiaAfshin** [awslabs/amazon-redshift-utils#149]
Can AWS RedShift resource be used to access S3 objects?

I'd like to write a function that will import any given drop file from s3 directly into the cluster the UDF is running on.

Something like

```SQL
CREATE FUNCTION import_s3_object(full_path_to_s3 VARCHAR)
RETURNS varchar
IMMUTABLE AS $$
//COPY some_table FROM full_path_to_s3 
$$ LANGUAGE plpythonu
;
```

In doing so, I also would like the RedShift instance to not have to pass the credentials, but instead identify the role to be used that has the attached policies to access the file from RedShift.

To be explicit, I'd like my function to all together not have to do
```SQL
COPY public.some_table FROM 's3://some_bucket/drop_file.gz'
CREDENTIALS 'aws_access_key_id=...;aws_secret_access_key=...;token=...'     delimiter '\t' gzip NULL AS '\000' TRUNCATECOLUMNS;"
```

I'd like the function run the query as such:
``` SQL
COPY public.some_table FROM 's3://some_bucket/drop_file.gz'
iam_role 'arn:aws:iam::0123456789012:role/MyRedshiftRole'
AS '\000' TRUNCATECOLUMNS;"
```

So, having verbalized my question, my requirement is a function to 

```SQL
CREATE FUNCTION import_s3_object(S3_FULL_PATH VARCHAR)
RETURNS varchar
IMMUTABLE AS $$
//COPY public.some_table FROM 'S3_FULL_PATH'
//iam_role 'arn:aws:iam::0123456789012:role/MyRedshiftRole'
//AS '\000' TRUNCATECOLUMNS;"
$$ LANGUAGE plpythonu
;
```

**Comment by deanah** [comment]
Redshift UDFs don't have network access so there's no way for it to reach S3. That said I recommend you watch the Redshift forum in the coming months for an announcement that may interest you on this subject.

**Comment by zach-data** [comment]
In this case network access is limited for Redshift UDFs: http://docs.aws.amazon.com/redshift/latest/dg/udf-constraints.html

In the future, please route issues not relevant to the amazon-redshift-utils project to either the AWS support center or the AWS Redshift forums for a more timely response.
