### ISSUE TITLE
v_generate_tbl_ddl.sql Failing: Syntax Error

### ISSUE THREAD

**Issue by zachdb86** [awslabs/amazon-redshift-utils#152]
An error occurred when executing the SQL command:
CREATE OR REPLACE VIEW admin.v_generate_tbl_ddl
AS
SELECT
 schemaname
 ,tablename
 ,seq
 ,ddl
FROM
 (
 SELECT
  schemaname
  ,tablename
  ,seq
  ,ddl
...

[Amazon](500310) Invalid operation: syntax error at or near "SELECT";

Execution time: 0.1s

1 statement failed.

**Comment by zach-data** [comment]
Issue does not reproduce from psql 8.4. Can you provide steps to do so?
