### ISSUE TITLE
extra characters from v_generate_user_object_permissions

### ISSUE THREAD

**Issue by onyxraven** [awslabs/amazon-redshift-utils#154]
the `+` string is being added onto some (but not all) the generated grant lines for a table. it only shows up when a user has multiple rights on the given table.'

```
 GRANT SELECT ON public.tracking_offer TO user1;                 +
 GRANT UPDATE ON public.tracking_offer TO user1;
 GRANT SELECT ON public.tracking_offer TO user2;
 GRANT SELECT ON public.tracking_offer TO user3;
```

**Comment by timjell** [comment]
Tested with multiple grants on a table, each line has the correct text without any extra '+' characters.

Closing as unable to reproduce.
