### ISSUE TITLE
Can not deploy with build.sh

### ISSUE THREAD

**Issue by GetheBeber** [awslabs/amazon-redshift-utils#166]
Hello,

I try to install SnapshotManager with deploy.sh method but I can not because of an error while script execution : 

> Checking for an existing version of this function in AWS Lambda...
usage: aws [options] <command> <subcommand> [parameters]
aws: error: argument command: Invalid choice, valid choices are:...

Here is my command line :
./build.sh deploy <myARN> schedule every-8-hours.json

where every-8-hours.json is a config file based on given example.

Would need your precious help :)

Thanks in advance.

Bertrand.

**Comment by zachdb86** [comment]
You have not included a role-arn in you arguments.
`build.sh deploy <role-arn> schedule <config.json>`

**Comment by dannyteok** [comment]
What would be an example of <role-arn> ?
An error spat out the following:
Member must satisfy regular expression pattern: `arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+`

I have it as arn:aws:iam:123456789012:mylambda-sandbox-01

Any example of what this part must look like will help. Thanks!

**Comment by timjell** [comment]
Snapshot Manager has been deprecated. Closing this issue as no longer relevant.
