### ISSUE TITLE
Error :TypeError: coercing to Unicode: need string or buffer, bool found while running analyze-schema-compression.py

### ISSUE THREAD

**Issue by Ashish-1991** [awslabs/amazon-redshift-utils#167]
I am running into the mentioned error when I type the following to terminal

python analyze-schema-compression.py --db xxxxxx --db-user xxxxxx --db-host xxxxxx-xxxx.c2qf9lhaxxxx.us-west-2.redshift.amazonaws.com --db-port XXXX --output-file file-name.sql.

I am new to python , so any help would be great saver.

**Comment by cleaton** [comment]
I just had the same problem.

You have to specify the '--report-file' option, this is a new option that will generate a report that shows a diff of your current encoding values compared to the recommended ones.

**Comment by saeedma8** [comment]
[Amazon Redshift Column Encoding Utility](https://github.com/awslabs/amazon-redshift-utils/tree/master/src/ColumnEncodingUtility#amazon-redshift-column-encoding-utility) is now deprecated. Instead, please use Redshift's Automatic Table Optimization features through:

```
ALTER TABLE table_name ALTER SORTKEY AUTO;
ALTER TABLE table_name ALTER DISTSTYLE AUTO;
```
https://docs.aws.amazon.com/redshift/latest/dg/t_Creating_tables.html
