### ISSUE TITLE
Vacuum utility skipping tables with interleaved keys

### ISSUE THREAD

**Issue by miketaluc-bytecode** [awslabs/amazon-redshift-utils#184]
There appears to be a bug in the vacuum utility that's causing it to miss tables with interleaved sort keys when running the utility without specifying specific tables.  First, those tables while not needing to be resorted (per AWS documentation) do at least need to have deleted data cleared out, but the only query that doesn't filter out interleaved tables in the utility doesn't address the criteria of dead tuples.  What's more is that one query only returns tables with a skew of > 5 (skew can apparently be null in the svv_interleaved_columns table if it's never been vacuumed so can get missed altogether) whereas AWS recommends vacuum reindex for skews of greater than 1.4 (seems like this should be parameterized).  It also filters out those tables with fewer than 10k records in the stv_interleaved_counts table which if I understand it correctly represents the number of distinct column values in the sort key which seems an arbitrary value to choose to prevent over reindexing.  

I found through testing that ideally tables with interleaved keys should be vacuumed based on the unsorted value in svv_table_info then vacuum reindexed based on the interleaved_skew value in svv_interleaved_columns.  Running reindex's w/o first running regular vacuums can cause the skew value to be significantly high (not sure why) which will then cause another reindex the next time the utility runs.

**Comment by viesti** [comment]
Is this issue still relevant? Seems that vacuum utility does reindex as well now.

**Comment by miketaluc-bytecode** [comment]
@viesti this change was merged back in september.
