### ISSUE TITLE
connect() got an unexpected keyword argument 'keepalives'

### ISSUE THREAD

**Issue by alexnelsone** [awslabs/amazon-redshift-utils#186]
I'm attempting to run the script directly from the command line and receiving the error above.   I'm running with the following syntax (param values changed to obfuscate sensitive data):

python ./amazon-redshift-utils/src/ColumnEncodingUtility/analyze-schema-compression.py --db mydb --db-user adminuser --db-pwd xxxx --db-port 5439 --db-host clustername.us-east-1.redshift.amazonaws.com --output-file analyze-us-east-1 --report-file compress-us-east-1

**Comment by brianvoss** [comment]
+1 getting this as well on a new checkout.  removing all keepalive* keyword args allows the script to proceed

**Comment by rajivchodisetti** [comment]
Am also facing the same issue

**Comment by alexnelsone** [comment]
Similar to @brianvoss I got this working by removing any mention of keepalive from the pg8000 connect method.  This allows it to work but when I try to incorporate into a script it still complains about the keepalives.

For those looking for 'the fix' the issue is corrected by removing any reference to keepalives here:
    conn = pg8000.connect(user=db_user, host=db_host, port=db_port, database=db, password=db_pwd, ssl=ssl_option, timeout=None, keepalives=1, keepalives_idle=200, keepalives_interval=200, keepalives_count=5)

Turn this into:
    conn = pg8000.connect(user=db_user, host=db_host, port=db_port, database=db, password=db_pwd, ssl=ssl_option, timeout=None)

**Comment by IanMeyers** [comment]
This has been merged in https://github.com/awslabs/amazon-redshift-utils/commit/70f2a3b4786082464cef023338b84a11c3e2afc6.

**Comment by rpaterson** [comment]
This may have fixed the immediate problem, but it also disabled keepalive!  The analyze-schema-compression utility is slow enough that without keepalive it times out on some of my wider tables.  When I added back the keepalives options above it no longer times out.  I don't get the error described in this case - maybe it's OS-dependent or something?  I'm running on Ubuntu 16.04, Python 2.7.12

**Comment by IanMeyers** [comment]
We had to take the keepalives out due to a change in the pg8000 driver. Happy to take a pR to add it all back in

**Comment by rpaterson** [comment]
Ok here you go: https://github.com/awslabs/amazon-redshift-utils/pull/219

**Comment by etspaceman** [comment]
I'm getting the error again on the most recent commit.

**Comment by etspaceman** [comment]
keepalive arguments are not supported in pg8000.connect:

https://github.com/mfenniak/pg8000/blob/bdadf48379eb28b4de8cf716e593205054480b3e/pg8000/__init__.py#L43

**Comment by rpaterson** [comment]
I don't get any error for some reason, but adding back these parameters did not enable keepalive - see #224

**Comment by etspaceman** [comment]
@rpaterson you might be using an older version of the pg8000 driver. If you run this within the provided Dockerfile, it fails.

**Comment by rpaterson** [comment]
That sounds plausible.  Anyway even on my machine it doesn't actually "work", so may as well take it out.

**Comment by IanMeyers** [comment]
Let's move this to Issue 224
