### ISSUE TITLE
Max / min size in v_extended_table_info

### ISSUE THREAD

**Issue by dobomode** [awslabs/amazon-redshift-utils#190]
What is the difference and exact definition of maximum and minimum table size in `v_extended_table_info`?

https://github.com/awslabs/amazon-redshift-utils/blob/756453130b223ffd19a1a6fb67992644af868da0/src/AdminViews/v_extended_table_info.sql#L14

**Comment by fynixtech** [comment]
Minimum table size is the smallest amount of space a table can occupy. The smallest block size in RedShift is 1MB. When a table is created with EVEN or KEY based distribution, a block is allocated on each slice in the cluster for each column in the table (user cols + 3 system cols) and this block count is doubled if the table has a sort key (sorted and unsorted region). If using ALL distribution then a block is allocated on first slice in each node of the cluster for each column in the table.

e.g given a table with 7 user cols, a sort key, EVEN distribution and a 3 node dc1.large (2 slices per node).

Minimum table size = (7+3) * 2slices * 3nodes * 2 regions (sorted/unsorted) * 1MB = 120MB

Size in MB: Actual number of blocks provisioned for the table
Minimum table size: See above explanation
(percentage storage used): Size in MB/Total Storage * 100

https://aws.amazon.com/premiumsupport/knowledge-center/redshift-cluster-storage-space/
http://docs.aws.amazon.com/redshift/latest/dg/c_choosing_dist_sort.html

**Comment by dobomode** [comment]
Cool, very clear – thanks!
