### ISSUE TITLE
Redshift equivalent rollup() and grouping() sql functions

### ISSUE THREAD

**Issue by pavank1933** [awslabs/amazon-redshift-utils#202]
Trying to convert teradata bteq Sql scripts to redshift Sql. My current redshift postgres version is 8.0.2, redshift version is 1.0.1499. Current version of redshift does not support rollup(), grouping() functions. How to overcome and resolve this scenario. What are the equivalent redshift functions for them. Could anyone explain with some. Examples how to do

**Comment by joeharris76** [comment]
This would be better asked on the [Redshift forum](https://forums.aws.amazon.com/forum.jspa?forumID=155) or [StackOverflow](https://stackoverflow.com/questions/tagged/amazon-redshift). GitHub issues should be related to the code provided here.
