### ISSUE TITLE
analyze-vacuum-schema.py arguments not overriding defaults.

### ISSUE THREAD

**Issue by benbkoch** [awslabs/amazon-redshift-utils#208]
for example passing in --min-unsorted-pct does not overwrite the default value of 5.

**Comment by etspaceman** [comment]
Confirmed... defaults are hard-coded here and aren't overridden...:

https://github.com/awslabs/amazon-redshift-utils/blob/master/src/AnalyzeVacuumUtility/lib/analyze_vacuum.py#L10
