### ISSUE TITLE
v_generate_tbl_dd create statement doesn't have admin schema specified

### ISSUE THREAD

**Issue by HolzDBA** [awslabs/amazon-redshift-utils#21]
The DROP View statement specifies the admin schema but the CREATE statement doesn't.
--DROP VIEW admin.v_generate_tbl_ddl;

CREATE OR REPLACE VIEW v_generate_tbl_ddl

**Comment by ericfe** [comment]
fixing it

**Comment by IanMeyers** [comment]
Fixed in pull request 23
