### ISSUE TITLE
Handle billions of data in Source

### ISSUE THREAD

**Issue by njain006** [awslabs/amazon-redshift-utils#213]
Hello Team,
I am facing an issue with billions of data to be run the analyze compression on. 

It fails with error all the time? 

What can be done to mitigate this issue.?

**Comment by IanMeyers** [comment]
Hello - can you give us a bit more detail on what you are seeing? If you are running the column encoding utility, then often it's best to have it generate a script, and then you can run sub-sets of the tables when it's most suitable for you, rather than having to do them all at once.

**Comment by njain006** [comment]
Yeah, I had to generate the scripts and run in batches.
Thanks for the response

Thanks and Regards,
Nitin Jain
+1 (585) 733-6042
FIU-Business School
