### ISSUE TITLE
Vacuum query returning empty statement and causing tables not being vacuumed

### ISSUE THREAD

**Issue by fjavieralba** [awslabs/amazon-redshift-utils#214]
This is an issue regarding the `AnalyzeVacuumUtility`.

The following query:

```sql
SELECT 'vacuum FULL ' + "schema" + '."' + "table" + '" ; '
                                                   + '/* '+ ' Table Name : ' + "schema" + '."' + "table"
                                                   + '",  Size : ' + CAST("size" AS VARCHAR(10)) + ' MB,  Unsorted_pct : ' + decode("unsorted", null,'null')
                                                   + ',  Deleted_pct : ' + CAST("empty" AS VARCHAR(10)) +' */ ;' as statement,
                                         "table" as table_name
                                        FROM svv_table_info
                                        WHERE (unsorted > 5 OR empty > 5 or stats_off > 10)
                                            AND   size < 716800
                                            AND  "schema" = 'my_schema'
```

Is returning `NULL` values in the `statement` result field:

|statement|table_name|
|---|---|
||table_1|
||table_2|
||table_3|

That is caused by the `decode("unsorted", null,'null')`

If we substitute `decode("unsorted", null,'null')` by `CAST("unsorted" AS VARCHAR(10))`, the query returns the correct resultset:

```sql
SELECT 'vacuum FULL ' + "schema" + '."' + "table" + '" ; '
                                                   + '/* '+ ' Table Name : ' + "schema" + '."' + "table"
                                                   + '",  Size : ' + CAST("size" AS VARCHAR(10)) + ' MB,  Unsorted_pct : ' + CAST("unsorted" AS VARCHAR(10))
                                                   + ',  Deleted_pct : ' + CAST("empty" AS VARCHAR(10)) +' */ ;' as statement,
                                         "table" as table_name
                                        FROM svv_table_info
                                        WHERE (unsorted > 5 OR empty > 5 or stats_off > 10)
                                            AND   size < 716800
                                            AND  "schema" = 'my_schema'
```

|statement|table_name|
|---|---|
|vacuum FULL audiences."table_1" ; /*  Table Name : my_schema."table_1",  Size : 131999 MB,  Unsorted_pct : 16.36,  Deleted_pct : 0 */ ;|table_1|
|vacuum FULL audiences."table_2" ; /*  Table Name : my_schema."table_2",  Size : 46624 MB,  Unsorted_pct : 57.65,  Deleted_pct : 0 */ ;|table_2|
|vacuum FULL audiences."table_3" ; /*  Table Name : my_schema."table_3",  Size : 88889 MB,  Unsorted_pct : 15.63,  Deleted_pct : 0 */ ;|table_3|

**Comment by IanMeyers** [comment]
Looks like we needed 'coalesce' rather than 'decode'. Sorry about that. Tested fix in https://github.com/awslabs/amazon-redshift-utils/commit/375fcef293025931fc55d98b895cd9053deb4f80.

**Comment by fjavieralba** [comment]
wow, that was quick! 😄
Thanks!
