### ISSUE TITLE
Can we create SSO for Redshift access

### ISSUE THREAD

**Issue by OmkarLakhe** [awslabs/amazon-redshift-utils#215]
Hi All,

I want to implement Single Sing on in one of my projects. 
can any one help me with the same. If anyone has already implemented it or has worked on it on how to implement that will be helpful.

Regards,
Omkar Lakhe

**Comment by fynixtech** [comment]
http://docs.aws.amazon.com/redshift/latest/mgmt/generating-user-credentials.html
