### ISSUE TITLE
Preserve table owner

### ISSUE THREAD

**Issue by rpaterson** [awslabs/amazon-redshift-utils#216]
The analyze-schema-compression util should preserve the table owner.

**Comment by IanMeyers** [comment]
Hello - right you are! What are you seeing, and how are you calling the utility? This should already be the case so want to dig in and find why this would happen.

**Comment by rpaterson** [comment]
The utility makes no effort to preserve the owner.  I've got a fix ready, will open a PR in a minute.

**Comment by IanMeyers** [comment]
The table owner is set to the provided `analyze-schema` value, unless this is not provided, in which case it defaults to 'public' or the value of `target-schema`. If you don't specify a `target-schema` and analyse everything your user can see, then the script will generate against 'public' which is incorrect.

**Comment by rpaterson** [comment]
IMO it should preserve the original table's owner, which may not be the same as the owner of it's current schema nor the target schema.

**Comment by IanMeyers** [comment]
Agreed - if the `target-schema` isn't provided, then that's what should happen.
