### ISSUE TITLE
Insert in to compressed table in SORTKEY order

### ISSUE THREAD

**Issue by rpaterson** [awslabs/amazon-redshift-utils#218]
The analyze-schema-compression utility creates a copy of the table and then loads it with `INSERT INTO <copy> SELECT * FROM <original>`.  I'm not sure about this but isn't that going to cause the table to be unsorted if it has a SORTKEY?  Should the utility be doing something like `INSERT INTO <copy> SELECT * FROM <original> ORDER BY <sortkey>`?

**Comment by rpaterson** [comment]
See http://docs.aws.amazon.com/redshift/latest/dg/c_best-practices-sort-key-order.html

**Comment by IanMeyers** [comment]
Indeed - looking.

**Comment by IanMeyers** [comment]
an easy fix - 2 mins

**Comment by IanMeyers** [comment]
https://github.com/awslabs/amazon-redshift-utils/commit/9b876a17088591e292a5a3245352c6f738abf367

**Comment by rpaterson** [comment]
Fix looks good, but did you confirm it's actually a problem?  I guess it does no harm...

**Comment by fynixtech** [comment]
if a table has a sort key defined, the data will be sorted with INSERT INTO <copy> SELECT * FROM <original>, no need to perform an order by. A sort key will always enforce sortedness. ORDER BY will only be needed if you don't define a sortkey but want the data to be sorted in a specific order.

**Comment by rpaterson** [comment]
Well it is possible for the rows to become unsorted if you don't insert in order - see Redshift docs above.  However their [deep copy doc](http://docs.aws.amazon.com/redshift/latest/dg/performing-a-deep-copy.html) (which is what this script is doing) says: `A deep copy recreates and repopulates a table by using a bulk insert, which automatically sorts the table.`  So based on that it appears that adding an `ORDER BY` to the SELECT is not necessary.

**Comment by fynixtech** [comment]
The first load to a table with a sort key will sort the data and load it into the SORTED region of the table. The next time you load the non-empty table, Redshift will sort the new data and load it into the UNSORTED region and this goes on until you VACUUM SORT/VACUUM FULL/DEEP COPY the table. At that time both regions will be merged.
The doc you referenced is in relation to COPY command. If your table meets the following conditions below, the COPY command will load subsequent data directly into the SORTED region and eliminate the need for a VACUUM/DEEP COPY to merge the regions.

- The table uses a compound sort key with only one sort column.
- The sort column is NOT NULL.
- The table is 100 percent sorted or empty.
- All the new rows are higher in sort order than the existing rows, including rows marked for deletion.

http://docs.aws.amazon.com/redshift/latest/dg/vacuum-load-in-sort-key-order.html

**Comment by rpaterson** [comment]
Thanks for the info!

**Comment by fynixtech** [comment]
👍🏾

**Comment by IanMeyers** [comment]
Not encoding the first column in the sortkey is still the recommended behaviour.
