### ISSUE TITLE
top_queries.sql missing num_events column in subquery

### ISSUE THREAD

**Issue by HolzDBA** [awslabs/amazon-redshift-utils#22]
This error is generated when I run the script. I added the bolded text below to get it running.

ERROR: 42703: column alrt.num_events does not exist */

left outer join ( select query, trim(split_part(event,':',1)) as event **,COUNT(*) AS num_events** from STL_ALERT_EVENT_LOG where event_time >=  dateadd(day, -7, current_Date)  group by query, trim(split_part(event,':',1)) ) as alrt on alrt.query = stl_query.query

**Comment by IanMeyers** [comment]
Fixed in pull request 23
