### ISSUE TITLE
RedshiftAutomation-LambdaRedshiftAutomation-xxxxxx error during AnalyzeVacuumUtility/analyze_vacuum.py

### ISSUE THREAD

**Issue by saunakc** [awslabs/amazon-redshift-utils#221]
The lambda function gets invoked and does run the vaccum on the 1st table selected by the AnalyzeVacuumUtility however it aborts during the analyze process as with error "ProgrammingError: (u'ERROR', u'42P01', u'relation "infrabi.d_infr_part_category_dim " does not exist', u'/home/ec2-user/padb/src/pg/src/backend/catalog/namespace.c', u'230', u'RangeVarGetRelid', u'', u'')". Any pointer on this.

Error log from the CW log below-

"/var/task/lib/amazon-redshift-monitoring/redshift_monitoring.py:319: SyntaxWarning: name 'debug' is assigned to before global declaration
global debug
START RequestId: 8b31682c-e130-11e7-b8b8-c1427100db8d Version: $LATEST
Running AnalyzeVacuumUtility
-- 2017-12-15 00:40:28.234874 [1] [1] Running 1 out of 1 commands: set search_path = '$user',public,infrabi
-- 2017-12-15 00:40:28.253097 [1] Success.
-- 2017-12-15 00:40:28.253197 [1] [1] Running 1 out of 1 commands: set statement_timeout = '36000000'
-- 2017-12-15 00:40:28.256852 [1] Success.
-- 2017-12-15 00:40:28.256947 [1] Connected to infradw1.ccbt60rdg6mc.us-east-1.redshift.amazonaws.com:8192:infradw as infrabi_user
-- 2017-12-15 00:40:28.257026 [1] Extracting Candidate Tables for vacuum based on stl_alert_event_log...
-- 2017-12-15 00:41:08.625947 [1] Found 8 Tables requiring Vacuum and flagged by alert
-- 2017-12-15 00:41:08.626128 [1] [1] Running 1 out of 16 commands: vacuum FULL infrabi."d_infr_physical_site_dim" ; /* Table Name : infrabi."d_infr_physical_site_dim", Size : 235 MB, Unsorted_pct : null, Deleted_pct : 0 */ ;
-- 2017-12-15 00:42:21.167683 [1] Success.
-- 2017-12-15 00:42:21.167760 [1] [1] Running 2 out of 16 commands: analyze infrabi."d_infr_physical_site_dim "
Traceback (most recent call last):
File "/var/task/lib/AnalyzeVacuumUtility/analyze_vacuum.py", line 159, in run_commands
cursor.execute(c)
File "/var/task/lib/pg8000/core.py", line 907, in execute
self._c.execute(self, operation, args)
File "/var/task/lib/pg8000/core.py", line 2017, in execute
self.handle_messages(cursor)
File "/var/task/lib/pg8000/core.py", line 2094, in handle_messages
raise self.error
ProgrammingError: (u'ERROR', u'42P01', u'relation "infrabi.d_infr_physical_site_dim " does not exist', u'/home/ec2-user/padb/src/pg/src/backend/catalog/namespace.c', u'230', u'RangeVarGetRelid', u'', u'')

-- 2017-12-15 00:42:24.211042 [1] Extracting Candidate Tables for vacuum ...
With autocommit on, it's not possible to retrieve more rows than the pg8000 cache size, as the portal is closed when the transaction is closed.: InterfaceError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 167, in event_handler
safe_get("min_interleaved_cnt",config_detail)
File "/var/task/lib/AnalyzeVacuumUtility/analyze_vacuum.py", line 559, in run_analyze_vacuum
min_interleaved_cnt if min_interleaved_cnt is not None else _min_interleaved_cnt)
File "/var/task/lib/AnalyzeVacuumUtility/analyze_vacuum.py", line 309, in run_vacuum
vacuum_statements = execute_query(conn, get_vacuum_statement)
File "/var/task/lib/AnalyzeVacuumUtility/analyze_vacuum.py", line 44, in execute_query
cursor.execute(query)
File "/var/task/lib/pg8000/core.py", line 907, in execute
self._c.execute(self, operation, args)
File "/var/task/lib/pg8000/core.py", line 2021, in execute
"With autocommit on, it's not possible to retrieve more "
InterfaceError: With autocommit on, it's not possible to retrieve more rows than the pg8000 cache size, as the portal is closed when the transaction is closed.

END RequestId: 8b31682c-e130-11e7-b8b8-c1427100db8d
REPORT RequestId: 8b31682c-e130-11e7-b8b8-c1427100db8d	Duration: 134694.47 ms	Billed Duration: 134700 ms Memory Size: 192 MB	Max Memory Used: 40 MB	
START RequestId: 8b31682c-e130-11e7-b8b8-c1427100db8d Version: $LATEST
Running AnalyzeVacuumUtility
-- 2017-12-15 00:43:45.614806 [1] [1] Running 1 out of 1 commands: set search_path = '$user',public,infrabi
-- 2017-12-15 00:43:45.633126 [1] Success.
-- 2017-12-15 00:43:45.633188 [1] [1] Running 1 out of 1 commands: set statement_timeout = '36000000'
-- 2017-12-15 00:43:45.636695 [1] Success.
-- 2017-12-15 00:43:45.636751 [1] Connected to infradw1.ccbt60rdg6mc.us-east-1.redshift.amazonaws.com:8192:infradw as infrabi_user
-- 2017-12-15 00:43:45.636799 [1] Extracting Candidate Tables for vacuum based on stl_alert_event_log...
-- 2017-12-15 00:44:04.347928 [1] Found 7 Tables requiring Vacuum and flagged by alert
-- 2017-12-15 00:44:04.348074 [1] [1] Running 1 out of 14 commands: vacuum FULL infrabi."d_infr_part_category_dim" ; /* Table Name : infrabi."d_infr_part_category_dim", Size : 920 MB, Unsorted_pct : null, Deleted_pct : 0 */ ;
-- 2017-12-15 00:44:49.397543 [1] Success.
-- 2017-12-15 00:44:49.397616 [1] [1] Running 2 out of 14 commands: analyze infrabi."d_infr_part_category_dim "
Traceback (most recent call last):
File "/var/task/lib/AnalyzeVacuumUtility/analyze_vacuum.py", line 159, in run_commands
cursor.execute(c)
File "/var/task/lib/pg8000/core.py", line 907, in execute
self._c.execute(self, operation, args)
File "/var/task/lib/pg8000/core.py", line 2017, in execute
self.handle_messages(cursor)
File "/var/task/lib/pg8000/core.py", line 2094, in handle_messages
raise self.error
ProgrammingError: (u'ERROR', u'42P01', u'relation "infrabi.d_infr_part_category_dim " does not exist', u'/home/ec2-user/padb/src/pg/src/backend/catalog/namespace.c', u'230', u'RangeVarGetRelid', u'', u'')

-- 2017-12-15 00:44:52.518802 [1] Extracting Candidate Tables for vacuum ...
With autocommit on, it's not possible to retrieve more rows than the pg8000 cache size, as the portal is closed when the transaction is closed.: InterfaceError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 167, in event_handler
safe_get("min_interleaved_cnt",config_detail)
File "/var/task/lib/AnalyzeVacuumUtility/analyze_vacuum.py", line 559, in run_analyze_vacuum
min_interleaved_cnt if min_interleaved_cnt is not None else _min_interleaved_cnt)
File "/var/task/lib/AnalyzeVacuumUtility/analyze_vacuum.py", line 309, in run_vacuum
vacuum_statements = execute_query(conn, get_vacuum_statement)
File "/var/task/lib/AnalyzeVacuumUtility/analyze_vacuum.py", line 44, in execute_query
cursor.execute(query)
File "/var/task/lib/pg8000/core.py", line 907, in execute
self._c.execute(self, operation, args)
File "/var/task/lib/pg8000/core.py", line 2021, in execute
"With autocommit on, it's not possible to retrieve more "
InterfaceError: With autocommit on, it's not possible to retrieve more rows than the pg8000 cache size, as the portal is closed when the transaction is closed.

END RequestId: 8b31682c-e130-11e7-b8b8-c1427100db8d
REPORT RequestId: 8b31682c-e130-11e7-b8b8-c1427100db8d	Duration: 79255.93 ms	Billed Duration: 79300 ms Memory Size: 192 MB	Max Memory Used: 40 MB	
START RequestId: 8b31682c-e130-11e7-b8b8-c1427100db8d Version: $LATEST
Running AnalyzeVacuumUtility
-- 2017-12-15 00:47:03.041347 [1] [1] Running 1 out of 1 commands: set search_path = '$user',public,infrabi
-- 2017-12-15 00:47:03.055378 [1] Success.
-- 2017-12-15 00:47:03.055421 [1] [1] Running 1 out of 1 commands: set statement_timeout = '36000000'
-- 2017-12-15 00:47:03.059218 [1] Success.
-- 2017-12-15 00:47:03.059257 [1] Connected to infradw1.ccbt60rdg6mc.us-east-1.redshift.amazonaws.com:8192:infradw as infrabi_user
-- 2017-12-15 00:47:03.059292 [1] Extracting Candidate Tables for vacuum based on stl_alert_event_log...
-- 2017-12-15 00:47:21.945211 [1] Found 6 Tables requiring Vacuum and flagged by alert
-- 2017-12-15 00:47:21.945390 [1] [1] Running 1 out of 12 commands: vacuum FULL infrabi."d_infr_part_type_dim" ; /* Table Name : infrabi."d_infr_part_type_dim", Size : 1000 MB, Unsorted_pct : null, Deleted_pct : 0 */ ;
-- 2017-12-15 00:48:05.219724 [1] Success.
-- 2017-12-15 00:48:05.219844 [1] [1] Running 2 out of 12 commands: analyze infrabi."d_infr_part_type_dim "
Traceback (most recent call last):
File "/var/task/lib/AnalyzeVacuumUtility/analyze_vacuum.py", line 159, in run_commands
cursor.execute(c)
File "/var/task/lib/pg8000/core.py", line 907, in execute
self._c.execute(self, operation, args)
File "/var/task/lib/pg8000/core.py", line 2017, in execute
self.handle_messages(cursor)
File "/var/task/lib/pg8000/core.py", line 2094, in handle_messages
raise self.error
ProgrammingError: (u'ERROR', u'42P01', u'relation "infrabi.d_infr_part_type_dim " does not exist', u'/home/ec2-user/padb/src/pg/src/backend/catalog/namespace.c', u'230', u'RangeVarGetRelid', u'', u'')

-- 2017-12-15 00:48:08.274854 [1] Extracting Candidate Tables for vacuum ...
With autocommit on, it's not possible to retrieve more rows than the pg8000 cache size, as the portal is closed when the transaction is closed.: InterfaceError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 167, in event_handler
safe_get("min_interleaved_cnt",config_detail)
File "/var/task/lib/AnalyzeVacuumUtility/analyze_vacuum.py", line 559, in run_analyze_vacuum
min_interleaved_cnt if min_interleaved_cnt is not None else _min_interleaved_cnt)
File "/var/task/lib/AnalyzeVacuumUtility/analyze_vacuum.py", line 309, in run_vacuum
vacuum_statements = execute_query(conn, get_vacuum_statement)
File "/var/task/lib/AnalyzeVacuumUtility/analyze_vacuum.py", line 44, in execute_query
cursor.execute(query)
File "/var/task/lib/pg8000/core.py", line 907, in execute
self._c.execute(self, operation, args)
File "/var/task/lib/pg8000/core.py", line 2021, in execute
"With autocommit on, it's not possible to retrieve more "
InterfaceError: With autocommit on, it's not possible to retrieve more rows than the pg8000 cache size, as the portal is closed when the transaction is closed.

END RequestId: 8b31682c-e130-11e7-b8b8-c1427100db8d
REPORT RequestId: 8b31682c-e130-11e7-b8b8-c1427100db8d	Duration: 77536.67 ms	Billed Duration: 77600 ms Memory Size: 192 MB	Max Memory Used: 41 MB	
"

**Comment by IanMeyers** [comment]
I've made a bunch of changes recently - can you resync and see if this is still an issue?
