### ISSUE TITLE
ColumnEncodingUtility not using TCP keepalive

### ISSUE THREAD

**Issue by rpaterson** [awslabs/amazon-redshift-utils#224]
The Column Encoding Utility is not using TCP keepalive.  It tries to configure pg8000 to do it: https://github.com/awslabs/amazon-redshift-utils/blob/b5b24a747cd6f3ff29182675384554e7c30bfb2c/src/ColumnEncodingUtility/analyze-schema-compression.py#L172-L174

... but it doesn't actually work.  I can see that running `netstat -to`:
```Shell
tcp        0      0 192.168.1.5:38990       ec2-52-205-239-16:11439 ESTABLISHED off (0.00/0/0)
```
(if keepalive were enabled it would say "keepalive" instead of "off").

Looking at the pg8000 docs, it doesn't mention those keepalive options: http://pythonhosted.org/pg8000/dbapi.html?highlight=connec#pg8000.connect

We need to enable KeepAlive - the utility keeps "hanging" trying to analyze large tables.

**Comment by rpaterson** [comment]
To be precise the symptom here is the ColumnEncodingUtility hangs after printing out `Analyzing Table <table name>`, but if you look in Redshift (e.g. with `SELECT * FROM stv_recents WHERE status = 'Running'`) there is no active query.

**Comment by rpaterson** [comment]
Here's the `connect(...)` method in pg8000 - it's ignoring those options: https://github.com/mfenniak/pg8000/blob/master/pg8000/__init__.py#L43

**Comment by rpaterson** [comment]
Looks like pg8000 accepts a `unix_sock` instead of a `host` - maybe the answer is to create a socket configured with KeepAlive and then pass it in there?

**Comment by IanMeyers** [comment]
Yep - agreed - I will start work on that now that the round of configuration changes are completed.

**Comment by rpaterson** [comment]
@IanMeyers any update on this?  I am blocked by this issue.

**Comment by IanMeyers** [comment]
Looks like my update to this issue was discarded - apologies.

The unix_sock argument is only for use when you want to connect with pg8000 directly from the server host, and cannot be used to accept an arbitrary TCP socket. I did test this and there's no way to provide a bound socket reference for a remote host.

At this point, the only way I can see accomplishing the goal of the ticket is for the tcp keepalive feature to be re-added to pg8000.

Very open to other ideas though.

**Comment by rpaterson** [comment]
:-(  Is there any workaround?  IIRC somewhere in the Redshift docs it mentions keepAlive isn't necessary if you connect to Redshift from EC2?

**Comment by rpaterson** [comment]
https://docs.aws.amazon.com/redshift/latest/mgmt/connecting-firewall-guidance.html. I'm not sure if that's relevant tho.

**Comment by IanMeyers** [comment]
It is possible that firewall devices can incorrectly early terminate sessions, and so making sure that your border is configured as in the above document is essential. I would suggest that running this from EC2 is a good test to run, and also consider using [Redshift Automation](https://github.com/awslabs/amazon-redshift-utils/tree/master/src/RedshiftAutomation) utils to run from AWS Lambda?

**Comment by rpaterson** [comment]
Lambda definitely isn't going to work, there's an absolute time limit of only a few minutes.  But I'll try EC2.

**Comment by pvbouwel** [comment]
@rpaterson the changes that have just been merged should help you.  You'd still need to configure the parameters that are explained in the doc you mentioned https://docs.aws.amazon.com/redshift/latest/mgmt/connecting-firewall-guidance.html as the Linux defaults might not be aggressive enough if your network path has hops that keep state for a very short time.

**Comment by rpaterson** [comment]
@pvbouwel fantastic thank you!  I'll give it a go tomorrow and report back.

**Comment by rpaterson** [comment]
Confirmed @pvbouwel's fix works, thanks again!
