### ISSUE TITLE
AnalyzeVacuumUtility don't take account require ssl parameter 

### ISSUE THREAD

**Issue by xyklex** [awslabs/amazon-redshift-utils#232]
I was testing the `analyze-vacuum-schema.py` script against a cluster with a custom parameter group doing `require_ssl=true`.

But using the flag `--require-ssl true` doesn't work, it shows the next error:
 
```
Exception on Connect to Cluster: (u'FATAL', u'28000', u'no pg_hba.conf entry for host "::ffff:", user "master-user", database "master-db", SSL off', u'/home/ec2-user/padb/src/pg/src/backend/libpq/auth.c', u'466', u'ClientAuthentication')
Unable to connect to Cluster Endpoint
Traceback (most recent call last):
  File "/opt/aws-redshift-utils/src/AnalyzeVacuumUtility/analyze-vacuum-schema.py", line 258, in <module>
    main(sys.argv)
  File "/opt/aws-redshift-utils/src/AnalyzeVacuumUtility/analyze-vacuum-schema.py", line 249, in main
    result = analyze_vacuum.run_analyze_vacuum(**args)
  File "/opt/aws-redshift-utils/src/AnalyzeVacuumUtility/lib/analyze_vacuum.py", line 577, in run_analyze_vacuum
    raise Exception("No Connection was established")
Exception: No Connection was established
```

I found the issue is with [this line](https://github.com/awslabs/amazon-redshift-utils/blob/898825e6cec20bf12b86ec4f0e8d2758a75fc88b/src/AnalyzeVacuumUtility/lib/analyze_vacuum.py#L574) Specifically when it try to get the `SSL` config value in [this file](https://github.com/awslabs/amazon-redshift-utils/blob/898825e6cec20bf12b86ec4f0e8d2758a75fc88b/src/AnalyzeVacuumUtility/analyze-vacuum-schema.py#L158), it don't find any `ssl_option` because is defined as an alias, so I see there's a recent [new file](https://github.com/awslabs/amazon-redshift-utils/blob/898825e6cec20bf12b86ec4f0e8d2758a75fc88b/src/config_constants.py#L25) with the config primary values and aliases and a method to get them both, @IanMeyers is working on it, so I think, will have a solution for this soon, I open this issue for someone having the same error while the issue persist, I could help with a PR @IanMeyers if you could share an overview for you solution and if is something else to finish it.

**Comment by IanMeyers** [comment]
This should be fixed in https://github.com/awslabs/amazon-redshift-utils/commit/999e49faa94a7bcea9719fa0566f243470ef3c23

**Comment by keithslater** [comment]
I can confirm that it's working now

**Comment by IanMeyers** [comment]
Great!

**Comment by xyklex** [comment]
Thank you @IanMeyers

**Comment by MatchaBlast** [comment]
Hi @IanMeyers ,

I am running into the same issue using docker execution. Can you please take a look?

```
{'require_ssl': 'TRUE', 'max_unsorted_pct': '50', 'max_table_size_mb': 10000, 'min_interleaved_skew': '1.4', 'stats_off_pct': '10', 'db_user': 'abc', 'db': 'xyz', 'db_pwd': 'xyz', 'predicate_cols': 'false', 'db_port': 8192, 'vacuum_flag': True, 'suppress_cloudwatch': 'false', 'db_host': 'xyz.us-east-1.redshift.amazonaws.com', 'analyze_flag': True, 'schema_name': 'public', 'ignore_errors': 'false', 'debug': 'false', 'vacuum_parameter': 'full', 'slot_count': '1', 'min_interleaved_cnt': 0, 'min_unsorted_pct': '5'}
-- 2020-07-22 13:46:29.141167 [9] Connect xyz.us-east-1.redshift.amazonaws.com:8192:xyz:xyz
Exception on Connect to Cluster: (u'FATAL', u'28000', u'no pg_hba.conf entry for host "::ffff", user "xyz", database "xyz", SSL off', u'/home/ec2-user/padb/src/pg/src/backend/libpq/auth.c', u'465', u'ClientAuthentication')
Unable to connect to Cluster Endpoint
Traceback (most recent call last):
  File "AnalyzeVacuumUtility/analyze-vacuum-schema.py", line 140, in <module>
    main(sys.argv)
  File "AnalyzeVacuumUtility/analyze-vacuum-schema.py", line 131, in main
    result = analyze_vacuum.run_analyze_vacuum(**args)
  File "AnalyzeVacuumUtility/lib/analyze_vacuum.py", line 694, in run_analyze_vacuum
    raise Exception("No Connection was established")
Exception: No Connection was established

```

Thank you,
