### ISSUE TITLE
analyze-flag and vacuum-flag not defaulting to true

### ISSUE THREAD

**Issue by keithslater** [awslabs/amazon-redshift-utils#236]
You have to manually specify vacuum-flag and analyze-flag even though the default value is true. If not you receive these messages -

-- 2018-01-04 10:10:44.828526 [13383] Vacuum flag arg is not set. Vacuum not performed.
-- 2018-01-04 10:10:44.828535 [13383] Analyze flag arg is set as False. Analyze is not performed.

**Comment by IanMeyers** [comment]
Can you drop me the command line options you are supplying? If you don't supply --analyze-flag or --vacuum-flag, then it shouldn't do anything now

**Comment by keithslater** [comment]
Yes that is what is happening. The documentation says that the default values of those are true - https://github.com/awslabs/amazon-redshift-utils/tree/master/src/AnalyzeVacuumUtility

**Comment by IanMeyers** [comment]
Gotcha

**Comment by IanMeyers** [comment]
Updated the docs in https://github.com/awslabs/amazon-redshift-utils/commit/b9759dc11a1eac18bc69a34bb5b7da967057cbe6
