### ISSUE TITLE
Unsafe migration order can cause lost data

### ISSUE THREAD

**Issue by jklukas** [awslabs/amazon-redshift-utils#24]
Based on the description in https://github.com/awslabs/amazon-redshift-utils/tree/master/src/ColumnEncodingUtility#data-migration, there's potential for data loss. The table that's getting migrated won't get locked until the `ALTER TABLE` statement that first modifies it. In between, other transactions could be writing to the table. None of those updates will be present in the final table once the migration transaction commits.

Would you consider moving the rename of the existing table to be the first thing that happens in order to lock the table early and prevent the potential for loss of updates?

See https://www.simple.com/engineering/safe-migrations-with-redshift for a more detailed discussion of this possibility.

**Comment by IanMeyers** [comment]
Hi Jeff,

Thanks for the interest, and you are exactly right. The impact of changing the order of the alter table vs migration is quite high in the codebase, but we can easily lock the table being analysed at the start of the transaction. Working on that now.

Regards,

Ian

**Comment by jklukas** [comment]
Thanks so much for looking into this!

One of our big pain points with Redshift has been that as we understand the platform better, we realize we need to make changes to dist keys, sort keys, etc, and we've been doing that in an ad hoc way so far. We definitely have a need for a tool that can extract the current structure of a table, let you make some changes, and do the inserting, renaming, etc. to have the new structure take effect.

It looks like this migration tool has most of the bits and pieces we need, so I'd love to see it generalized to handling more than just changing compression encodings. I'm going to read through it some more to see if we can adapt it for a more general use case.

**Comment by IanMeyers** [comment]
Fixed in .9.1.3.4
