### ISSUE TITLE
NameError: global name 'cw' is not defined

### ISSUE THREAD

**Issue by wjordan** [awslabs/amazon-redshift-utils#248]
Running `ColumnEncodingUtility` with `do_execute` option currently throws the following undefined-variable error after successfully executing changes, but before emitting metrics to CloudWatch:

```
Exception global name 'cw' is not defined during analysis of [table]
Traceback (most recent call last):
  File "ColumnEncodingUtility/analyze-schema-compression.py", line 795, in analyze
    if cw is not None:
NameError: global name 'cw' is not defined

Error in worker thread: return code 1. Exiting.
Done
```

This issue seems like a possible regression from 9667686dac6f3dce48ab71b1cf87754813204a71, where `cw` global was renamed to `suppress_cw` but the rename wasn't correctly applied to all instances of this variable.

**Comment by IanMeyers** [comment]
ugh - sorry - please resync to https://github.com/awslabs/amazon-redshift-utils/commit/113c3304679d45360b7d76b4e4be05368da60d27 and retry.
