### ISSUE TITLE
Support for PGPASSWORD and other environment variables

### ISSUE THREAD

**Issue by jklukas** [awslabs/amazon-redshift-utils#25]
Folks at our organization typically use PGHOST, PGUSER, etc. when running command line tools to access Redshift or Postgresql. It would be nice to have `analyze-schema-compression.py` check for these so that the `--db-host`, etc. command line arguments don't need to be specified.

I'd be willing to make a PR for this. Do you consider PRs from the community?

**Comment by IanMeyers** [comment]
Yeah, they are very welcome. This sounds like a reasonable feature and I'll be happy to accept the request.

**Comment by IanMeyers** [comment]
Was super easy to do, so fixed this in .9.1.4
