### ISSUE TITLE
ColumnEncodingUtility should preserve foreign keys

### ISSUE THREAD

**Issue by rpaterson** [awslabs/amazon-redshift-utils#259]
The Column Encoding Utility drops all of the table's foreign keys.  Would be nice if it preserved them.  (Will have to recreate them after recreating the table).

**Comment by IanMeyers** [comment]
Agreed - I'll look into this

**Comment by IanMeyers** [comment]
So I've dug into this, and we do recreate FK's. Can you tell me what you are seeing that suggests this isn't working?

**Comment by rpaterson** [comment]
Ah I see my mistake.   I thought I had some foreign keys defined where I did not.  Sorry for the red herring.
