### ISSUE TITLE
Fail Fast if query fails

### ISSUE THREAD

**Issue by etspaceman** [awslabs/amazon-redshift-utils#261]
If a query fails in the analyze-vacuum Redshift utility, it currently continues on to the next query. Setting up alerting based on exit codes on this job is difficult as only the logs themselves will indicate the error. It also seems less-than ideal to continue processing if queries are failing.

The script should _at least_ introduce an option to fail-fast, if not fail-fast by default, if a query fails. If enabled, it should also throw an exception so that the application properly displays an exit code.

**Comment by IanMeyers** [comment]
Agreed - and as far as I can see all query level script execution exposes all native Exceptions (see https://github.com/awslabs/amazon-redshift-utils/blob/master/src/AnalyzeVacuumUtility/lib/analyze_vacuum.py#L51). Command execution however does swallow errors, which is probably wrong (https://github.com/awslabs/amazon-redshift-utils/blob/master/src/AnalyzeVacuumUtility/lib/analyze_vacuum.py#L169).

Where are you seeing the exception occur?

**Comment by etspaceman** [comment]
I had seen exceptions in basic things like trying to set the search path, which i see uses the run_commands function.

**Comment by IanMeyers** [comment]
Fixed in https://github.com/awslabs/amazon-redshift-utils/commit/e5c99a84197ba71ab4ef1d62a8ec5893ef39935e
