### ISSUE TITLE
pg_temp_n Schema error in admin.v_get_obj_priv_by_user

### ISSUE THREAD

**Issue by premjitsingh** [awslabs/amazon-redshift-utils#262]
Is it a good idea to filter out pg_temp_n Schema from the admin.v_get_obj_priv_by_user ddl

**Comment by joeharris76** [comment]
Can you please provide more context to your question?

**Comment by venkatveeramanidaasan** [comment]
Looks like the latest view got that fixed. Just redeployed it and the error vanished.
