### ISSUE TITLE
Redshift ETL Tools.

### ISSUE THREAD

**Issue by mukkamal** [awslabs/amazon-redshift-utils#264]
It would be handy to have a standardized version of ETL tools. I have written up the needed utilities and intend to contribute to this repo. Please grant me access to commit.

**Comment by IanMeyers** [comment]
Hello. This repository is administered as part of the AWS Organisation, so membership is only possible if you are an AWS employee. That said, we can certainly accept pull requests that are consistent with the architecture and direction for the tooling. For something like ETL tools, we have considered this extensively, and at this time would guide that downstream ELT from the load process be triggered via the SNS notifications currently supported. A project that utilised these notifications to create flexible transformations would be very cool, but right now would not be in the scope of this project.
