### ISSUE TITLE
redshift-etl-utility

### ISSUE THREAD

**Issue by mukkamal** [awslabs/amazon-redshift-utils#265]
Having a utility that takes in command line parameters for unload, copy and execute query would greatly reduce the time for ETL development. The set of utilities would use standard logging practice, notification and Error Handling. Scheduling them on cron, aws scheduler, airflow should then be very easy to do.

Redshift Copy Utility 
       Exports data from a source Redshift database to S3. 
        
       Usage: This utility needs two arguments the path of configs and the sql file. 
       python common_rs_copy.py <configuration> <sql_file> 
           <configuration> Local Path to configs file in configs directory 
           <target table> you want to load the data into. 
           <sql_file> Contains the select statement that needs to be used to download data. Can be in json or plain sql file. examples in sql folder. 
       Additionally you can specify: 
        the copy parameter with a -u/--copyParams parameter. These parms are delimiter, removequotes, escape etc. passed as a string. 
       Usage example with optional parameters 
       /git/amazon-redshift-utils/RedshiftETLTools/bin/common_rs_copy.py /git/amazon-redshift-utils/RedshiftETLTools/config/connect_configs public.events   s3://analytics-s3.company.com/events/2018-02-08_15-33-21/ removequotes  escape  delimiter ',' 

 Redshift Execute Query Utility 
       Executes a query in Redshift. 
        
       Usage: This utility needs one argument the path of the sql file. 
       python common_rs_execquery.py <configuration> <sql_file_path> 
           <configuration> Local Path to configs file in configs directory 
           <sql_file> Contains the select statement that needs to be used to download data.  Can be in json or plain sql file. examples in sql folder. 
       python  /git/amazon-redshift-utils/RedshiftETLTools/bin/common_rs_execquery.py /git/amazon-redshift-utils/RedshiftETLTools/config/connect_configs /git/amazon-redshift-utils/RedshiftETLTools/sql/events_hr_ul.sql 

Redshift Unload Utility 
       Exports data from a source Redshift database to S3. 
        
       Usage: This utility needs two arguments the path of configs and the sql file. 
       python common_rs_unload.py <configuration> <sql_file> 
           <configuration> Local Path to configs file in configs directory 
           <sql_file> Contains the select statement that needs to be used to download data. 
       Additionally you can specify: 
        the S3 Data Stage location with a -l/--dataDownloadPath parameter. 
        the unload parameter with a -u/--unloadParms parameter. These parms are delimiter, addquotes, escape etc. passed as a string. 
       Usage example with optional parameters 
       python  /git/amazon-redshift-utils/RedshiftETLTools/bin/common_rs_unload.py /git/amazon-redshift-utils/RedshiftETLTools/config/connect_configs /git/amazon-redshift-utils/RedshiftETLTools/sql/sov_aggregates.sql -l s3://analytics.riffsy.com/tp_events/2018-02-07_13/ 
    sys.exit(-1)

**Comment by timjell** [comment]
Closing issue as functionality now provided within Redshift
