### ISSUE TITLE
AnalyzeVacuumUtility schema-name regexp not working

### ISSUE THREAD

**Issue by kimmokantojarvi** [awslabs/amazon-redshift-utils#269]
Even though the documentation claims schema-name can not be expressed as Posix regular expression syntax. The problem is the search_path set in the beginning of the connection to Redshift. Search path only allows comma separated list of schemas. Same variable is used both for search path and SQLs to generate VACUUM commands. 

Solutions
a) create 2 different variables (one for search path and one for SQLs)
b) change variable to comma separated list of schemas and create regexp presentation of this into SQLs

Also to be noted that schema-name is not optional parameter. It is mandatory due to the fact that analyze_vacuum.py has dictionary search: kwargs[config_constants.SCHEMA_NAME]

**Comment by IanMeyers** [comment]
In my testing this didn’t block the utility actually working, but I do have a fix that I’ll hope to push today.

**Comment by IanMeyers** [comment]
Please resync to https://github.com/awslabs/amazon-redshift-utils/commit/d2d18347c45f42e1ec4685acfc2fd71541222247, which adds a pg_table_def mechanism for setting the search path based on regex.

**Comment by kimmokantojarvi** [comment]
I'm using the Automation module so I would rather wait it to get updated, but from the code/commits it seems to be much better now.

**Comment by viesti** [comment]
I took the opportunity to bring another Kimmo into the discussion :) 

We hit a problem where we specified a schema name with `--analyze-schema` (e.g. `dev`) and the tool used this value as a regex, and found tables in another schema where the argument appeared as a substring (e.g. `dev_<username>`). This resulted in the tool trying to overwrite a table in the target schema with one found from an unrelated schema.

From documentation, I'd expect that a plain literal is not interpreted as a regular expression:

> --analyze-schema      - The schema name or a regular expression pattern to resolve schemas for processing.

But this seems not to be the case.

To me, it looks like `schema_name` is not used as a regular expression in for example the [`get_grants`](https://github.com/awslabs/amazon-redshift-utils/blob/master/src/ColumnEncodingUtility/analyze-schema-compression.py#L262) function. But then again, it's used as a regex when [searching for tables](https://github.com/awslabs/amazon-redshift-utils/blob/master/src/ColumnEncodingUtility/analyze-schema-compression.py#L1004) even when a [table list was specified](https://github.com/awslabs/amazon-redshift-utils/blob/master/src/ColumnEncodingUtility/analyze-schema-compression.py#L990).

**Comment by IanMeyers** [comment]
So `get_grants` shouldn't use a regular expression, because it should be run table by table. The regex is only used to collect the initial table set before we start analysis. It sounds like you'd like to be able to suppress the use of regular expression matching for the case you mention. Regarding the table list, yes, we had the requirement submitted of supporting lists of regular expressions. I can imagine that performing an exact match with a command line argument is a reasonable requirement. 

Thoughts?
