### ISSUE TITLE
Running build.sh deploy results in Error.

### ISSUE THREAD

**Issue by dannyteok** [awslabs/amazon-redshift-utils#270]
So I found out what the <role-arn> must look like:
`arn:aws:lambda:us-east-1:126707828112:function:name-tocall-mylambdafn`

At the command line, `$ ./build.sh deploy <role-arn>` , it returns the following message:
You must set environment variable AWS_REGION to continue.

Fine. I edited build.sh and set that variable, and run it again.

```
Checking for an existing version of this function in AWS Lambda...

An error occurred (ResourceNotFoundException) when calling the GetFunction operation: Function not found: arn:aws:lambda:us-east-1:126707828112:function:RedshiftUtilsSnapshotManager

An error occurred (ValidationException) when calling the CreateFunction operation: 1 validation error detected: Value 'lambda_basic_vpc_exec' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+

```

What do I have to change to get this basically working? New to this.

**Comment by IanMeyers** [comment]
Can you please provide the full syntax you used to call the script? It looks like when you called this you provided the IAM role name instead of the role ARN. You can get this on the top of the IAM Role page.

**Comment by dannyteok** [comment]
Hi @IanMeyers 
Here is the full syntax

`$ ./build.sh deploy lambda_basic_vpc_exec arn:aws:lambda:us-east-1:126707828112:function:name-tocall-mylambdafn`

I  "lambda_basic_vpc_exec" is the role.

**Comment by IanMeyers** [comment]
OK - instead try:

`./build.sh deploy arn:aws:lambda:us-east-1:126707828112:function:name-tocall-mylambdafn schedule <my scheduling config file>`

**Comment by dannyteok** [comment]
what is the <my scheduling config file> ?
I have not done anything to have this and perhaps this may be the problem? Is it looking for a JSON file? If so, is this the every-2-hours-.json file ?

**Comment by IanMeyers** [comment]
You need to include a schedule definition, which I noted above as `<my scheduling config file>`. If you are happy for the module to run every 2 hours, then this file may be right, but you also need to specify the retention period. Depending where you are in the world, I may be able to do a screen share to walk you through getting all of this setup - can you email meyersi@amazon.com and we'll see if there's anything else you need?

**Comment by dannyteok** [comment]
I am happy for the module to run every 2 hours just to test things out. Sorry, I have no clue how to further configure from here on so any help will be very much appreciated. I'm based in London, UK., and please tell me how can we screen share and walk me through this config stage to get a working example?

**Comment by IanMeyers** [comment]
Sure, no problem. You'll just need a new file that specifies the properties for snapshots you desire:

```
{
	"targetResource":"energy-demo",
	"region":"eu-west-1",
	"namespace":"every-2-hours",
	"snapshotIntervalHours":2,
	"snapshotRetentionDays":1
}
```

 * `targetResource` is the name of the cluster that you want to control - you can manage many clusters with one configuration
* `region` is the AWS region where the cluster resides
* `namespace` allows you to uniquely identify the schedule
* `snapshotIntervalHours` specifies how often you want snapshots taken, which define your Recovery Point Objective
* `snapshotRetentionDays` specifies how many days worth of snapshots to retain, which will affect the cost of the overall snapshot storage.

**Comment by dannyteok** [comment]
Hi Ian,

That properties file is the every-2-hours.json file in
.../amazon-redshift-utils/src/SnapshotManager
We can use the original file, or another one I have created that points to
a specific Redshift cluster for "targetResource".

Let me know when we can begin.


Kind regards,

Danny Teok
Tel: +44 792 979 5499 (All day)
*t*: @dantvli
*in*: goo.gl/z9oS5P
*g+:*

**Comment by dannyteok** [comment]
Hi!
I think I must also mention that I'm doing this on a brand new EC2 instance running Ubuntu 16.04 LTS. The only things I have set up are:
Boto3
Shortuuid, and
Amazon-Redshift-Utils

I have tried running the following but it still failed:
`./build.sh deploy arn:aws:lambda:us-east-1:126707828112:function:name-tocall-mylambdafn schedule every-2-hours.json`

Since this is a Node.js handler, is it necessary to pre-configure some things related to this in my new environment? Any other ideas?

**Comment by IanMeyers** [comment]
In the main source directory you should also run `npm install`.

**Comment by dannyteok** [comment]
I've just done that.
```

├─┬ async@2.0.0-rc.5
│ └── lodash@4.17.5
└── moment@2.13.0

```

**Comment by IanMeyers** [comment]
OK - what's the failure message you are getting?

**Comment by dannyteok** [comment]
running npm install was successful. That was the output.
what's next?

**Comment by IanMeyers** [comment]
Hello - sorry for the delay in coming back to you. The good news is that you can now use the internal [deploy.yaml](src/SnapshotManager/deploy.yaml) to deploy the module, rather than using the build script. This was clearly too complicated and involved too many steps. Now, you should just be able to click the deploy stack button for the correct region in Snapshot Manager's [README.md](src/SnapshotManager/README.md), and not have to use the build and deploy script at all.

**Comment by dannyteok** [comment]
Awesome! I'll try it out and revert.
By the way, do I have to revert everything to original or it's okay to continue from where I have left it -- npm install ?

**Comment by IanMeyers** [comment]
No installation should be required, and what you've done shouldn't interfere with a deployment.

**Comment by timjell** [comment]
SnapshotManager is now deprecated. Closing this issue as no longer relevant.
