### ISSUE TITLE
Build failures for analyze-schema-compression.py due to aws_utils package

### ISSUE THREAD

**Issue by MatthewPorterGN** [awslabs/amazon-redshift-utils#271]
Attempting to build amazon-redshift-utils according to the documentation results in errors from a missing method in the "aws_utils" package. Building with Docker also fails, see below:

Using the install commands listed below on a base Linux EC2 AMI:
```
yum -y install git postgresql postgresql-devel gcc python-devel docker
yum -y update 
git clone https://github.com/awslabs/amazon-redshift-utils /usr/lib/amazon-redshift-utils
ln -s /usr/lib/amazon-redshift-utils/src/ColumnEncodingUtility/analyze-schema-compression.py .
easy_install pip
pip install -r /usr/lib/amazon-redshift-utils/src/requirements.txt PyGreSQL pygresql aws_utils
./analyze-schema-compression.py
```
Yields the following error:
```
$ python ./analyze-schema-compression.py 
Traceback (most recent call last):
  File "./analyze-schema-compression.py", line 60, in <module>
    import aws_utils
  File "/usr/lib/python2.7/dist-packages/aws_utils/__init__.py", line 4, in <module>
    from .sqs_consumer import SQSConsumer  # noqa
  File "/usr/lib/python2.7/dist-packages/aws_utils/sqs_consumer.py", line 4, in <module>
    from .exceptions import MissingQueueError
ImportError: cannot import name MissingQueueError
```
Adding a placeholder method in to that script:
```
sudo sh -c "echo '

class MissingQueueError(Exception):
    pass' >> /usr/lib/python2.7/dist-packages/aws_utils/exceptions.py"
```
Then results in a crash on a non-existent 'config_constants' package import
```
$ python ./analyze-schema-compression.py 
Traceback (most recent call last):
  File "./analyze-schema-compression.py", line 61, in <module>
    import config_constants
ImportError: No module named config_constants
```
Attempts to build and use the Dockerfile do not succeed either. Using the commands below:
```
cd /usr/lib/amazon-redshift-utils
service docker start
docker build -t amazon-redshift-utils .
sudo docker run --net host --rm -it \
-e DB=xyz \
-e DB_USER=xyz \
-e DB_PWD=xyz \
-e DB_HOST=xyz \
-e DB_PORT=5439 \
-e ANALYZE_SCHEMA=xyz \
-e TARGET_SCHEMA=xyz \
-e SLOT_COUNT=2 \
amazon-redshift-utils column-encoding
```
Wherein legitimate values replace 'xyz' results in an error that also originates from the aws_utils package:
```
Running column-encoding utility
Traceback (most recent call last):
  File "ColumnEncodingUtility/analyze-schema-compression.py", line 1209, in <module>
    main(sys.argv)
  File "ColumnEncodingUtility/analyze-schema-compression.py", line 1202, in main
    result_code = run()
  File "ColumnEncodingUtility/analyze-schema-compression.py", line 924, in run
    master_conn = get_pg_conn()
  File "ColumnEncodingUtility/analyze-schema-compression.py", line 192, in get_pg_conn
    aws_utils.set_search_paths(conn, schema_name, target_schema)
  File "ColumnEncodingUtility/../aws_utils.py", line 59, in set_search_paths
    if set_target_schema is not None and set_target_schema != schema_name:
NameError: global name 'schema_name' is not defined
Done
```

**Comment by IanMeyers** [comment]
Hello,

I'm not sure quite why you are building this way, as you're referencing a couple of dependencies that are not documented in requirements.txt. The Column Encoding utility doesn't use PyGreSQL, and instead uses pg8000, and aws_utils is an internally built script as opposed to something in pip. you should just be able to go to the src directory and run `pip install`.

Thx,

Ian

**Comment by MatthewPorterGN** [comment]
Hi,

The extra packages were just a few things I had added during the debugging process after the requirements file alone did not work. I wound up figuring out the issue after you mentioned the src directory change: The tool does not work when used as a symbolic link. It does install fine using the README method but it can't be run outside the src directory due to how source file locations are determined for the internally built scripts:
```
[root@ip-10-5-150-30 ec2-user]# pwd
/home/ec2-user
[root@ip-10-5-150-30 ec2-user]# ll -h
total 4.0K
lrwxrwxrwx 1 ec2-user ec2-user  86 Feb 27 17:07 analyze-schema-compression.py -> /usr/lib/amazon-redshift-utils/src/ColumnEncodingUtility/analyze-schema-compression.py
[root@ip-10-5-150-30 ec2-user]# ./analyze-schema-compression.py -h
Traceback (most recent call last):
  File "./analyze-schema-compression.py", line 60, in <module>
    import aws_utils
ImportError: No module named aws_utils
[root@ip-10-5-150-30 ec2-user]# cd /usr/lib/amazon-redshift-utils/src/ColumnEncodingUtility/
[root@ip-10-5-150-30 ColumnEncodingUtility]# ./analyze-schema-compression.py -h
option -h not recognized
Usage: analyze-schema-compression.py
       Generates a script to optimise Redshift column encodings on all tables in a schema

Arguments: --db                  - The Database to Use
           --db-user             - The Database User to connect to
           --db-pwd              - The Password for the Database User to connect to
           --db-host             - The Cluster endpoint
           --db-port             - The Cluster endpoint port (default 5439)
           --analyze-schema      - The Schema to be Analyzed (default public)
           --analyze-table       - A specific table to be Analyzed, if --analyze-schema is not desired
           --analyze-cols        - Analyze column width and reduce the column width if needed
           --new-dist-key        - Set a new Distribution Key (only used if --analyze-table is specified)
           --new-sort-keys       - Set a new Sort Key using these comma separated columns (Compound Sort key only , and only used if --analyze-table is specified)
           --target-schema       - Name of a Schema into which the newly optimised tables and data should be created, rather than in place
           --threads             - The number of concurrent connections to use during analysis (default 2)
           --output-file         - The full path to the output file to be generated
           --debug               - Generate Debug Output including SQL Statements being run
           --do-execute          - Run the compression encoding optimisation
           --slot-count          - Modify the wlm_query_slot_count from the default of 1
           --ignore-errors       - Ignore errors raised in threads when running and continue processing
           --force               - Force table migration even if the table already has Column Encoding applied
           --drop-old-data       - Drop the old version of the data table, rather than renaming
           --comprows            - Set the number of rows to use for Compression Encoding Analysis
           --query_group         - Set the query_group for all queries
           --ssl-option          - Set SSL to True or False (default False)
           --suppress-cloudwatch - Set to True to suppress CloudWatch Metrics being created when --do-execute is True
```
I can get the tool to work fine now that I have worked past this, however the Dockerfile version of the tool still fails when using equivalent commands to the Git-built version. The Docker build command set was pulled from the README so I doubt anything went wrong on my end, have you tested that out recently?

**Comment by IanMeyers** [comment]
this will be because you haven't cloned the entire repository, which includes the aws_utils package as a resource in a top level directory. When this happens, pip tries to install it from central.

**Comment by sheetalchauhan24** [comment]
Can you please list down all steps required to get amazon-redshift-utils on my EC2 machine.
Any correction in the steps mentioned above ?
yum -y install git postgresql postgresql-devel gcc python-devel docker
yum -y update 
git clone https://github.com/awslabs/amazon-redshift-utils /usr/lib/amazon-redshift-utils
ln -s /usr/lib/amazon-redshift-utils/src/ColumnEncodingUtility/analyze-schema-compression.py .
easy_install pip
pip install -r /usr/lib/amazon-redshift-utils/src/requirements.txt PyGreSQL pygresql aws_utils
./analyze-schema-compression.py

**Comment by bmedharametla-rythmos** [comment]
The Actual issue for getting **ImportError: cannot import name MissingQueueError** is you have created **aws_utils.py** in your source code and also we have **aws_utils module** externally. When the external module is installed in our machine the import will be the external module which is again having code issue. 

Not sure how they made the module available if it is having code issue.

I got the same import error, I have uninstalled the aws_utils module externally and successfully ran the utility script.

**Comment by IanMeyers** [comment]
Thanks for the info. I am now pushing 1.5 of the distribution that fixes this name conflict.

**Comment by bmedharametla-rythmos** [comment]
https://github.com/thuitaw/aws-utils/issues/1

**Comment by timjell** [comment]
Closing the issue as resolved in the conversation above
