### ISSUE TITLE
error while running analyze-schema-compression.py

### ISSUE THREAD

**Issue by iwasnobody** [awslabs/amazon-redshift-utils#272]
According to the following error info, it seems the tool can't run if the table hasn't description which means "table_comment = table_info[6]" is NULL

[root@ip-110-110-120-204 ColumnEncodingUtility]# ./analyze-schema-compression.py --db dms --db-user root --db-pwd XXXX --db-host "XXXX.cyirsgk0j39u.ap-northeast-1.redshift.amazonaws.com" --db-port 5439 --analyze-schema mydb --analyze-table dmstest1 --do-execute false
-- [3415] [3415] Running set statement_timeout = '1200000'
-- [3415] Success.
-- [3415] [3415] Running set application_name to 'ColumnEncodingUtility-v.9.3.2'
-- [3415] Success.
-- [3415] Connected to dms1.cyirsgk0j39u.ap-northeast-1.redshift.amazonaws.com:5439:dms as root
-- [3415] Analyzing Table 'dmstest1' for Columnar Encoding Optimisations with 1 Threads...
-- [3415] Analyzing 1 table(s) which contain allocated data blocks
Traceback (most recent call last):
  File "./analyze-schema-compression.py", line 1209, in <module>
    main(sys.argv)
  File "./analyze-schema-compression.py", line 1202, in main
    result_code = run()
  File "./analyze-schema-compression.py", line 1035, in run
    result.append(analyze(t))
  File "./analyze-schema-compression.py", line 389, in analyze
    table_comment = table_info[6]
IndexError: list index out of range

**Comment by IanMeyers** [comment]
Can you please sync to https://github.com/awslabs/amazon-redshift-utils/commit/d781376ca9399a004361fd6bcd6b76598589089f and retry. This has never been an issue in the past but I've added a check in case something has changed in how the dictionary returns this value.

**Comment by iwasnobody** [comment]
@IanMeyers 
The error problem seems to be solved after sync to d781376.
But the tool hasn't identify my table encode need to be optimized.
I create a table using raw encode and insert 1000000 rows into it.
---------------
CREATE TABLE IF NOT EXISTS mydb.redshift
(
id INTEGER encode raw,
name VARCHAR(30) encode raw
)
DISTSTYLE EVEN
----------------
running "analyze compression" shows id column should use delta encoding while name column should use zstd encoding
-----------------
But the result of running the tool tells me there is no need to optimize the encoding.

[root@ip-110-110-120-204 ColumnEncodingUtility]# ./analyze-schema-compression.py --db dms --db-user root --db-pwd XXX --db-host "XXX.cyirsgk0j39u.ap-northeast-1.redshift.amazonaws.com" --db-port 5439 --analyze-schema mydb --analyze-table redshift --do-execute true
-- [24552] [24552] Running set statement_timeout = '1200000'
-- [24552] Success.
-- [24552] [24552] Running set application_name to 'ColumnEncodingUtility-v.9.3.2'
-- [24552] Success.
-- [24552] Connected to dms1.cyirsgk0j39u.ap-northeast-1.redshift.amazonaws.com:5439:dms as root
-- [24552] Analyzing Table 'redshift' for Columnar Encoding Optimisations with 1 Threads...
-- [24552] Recommended encoding changes will be applied automatically...
-- [24552] Analyzing 1 table(s) which contain allocated data blocks
-- [24552] Table redshift.42 does not require encoding optimisation
-- [24552] Performed modification of 0 tables

Any ideas?
Thank you in advance!

**Comment by IanMeyers** [comment]
Hmm - strange. Can you add the `--debug true` option and send output?

**Comment by iwasnobody** [comment]
@IanMeyers 
Following is the output after adding --debug true

[root@ip-110-110-120-204 ColumnEncodingUtility]# ./analyze-schema-compression.py --db dms --db-user root --db-pwd XXX --db-host "XXX.cyirsgk0j39u.ap-northeast-1.redshift.amazonaws.com" --db-port 5439 --analyze-schema mydb --analyze-table redshift --do-execute true --debug true
-- [26485] debug = True
-- [26485] db_host = dms1.cyirsgk0j39u.ap-northeast-1.redshift.amazonaws.com
-- [26485] Redshift Column Encoding Utility Configuration
-- [26485] Created Cloudwatch Emitter in us-east-1
-- [26485] Connect [26485] dms1.cyirsgk0j39u.ap-northeast-1.redshift.amazonaws.com:5439:dms:root
-- [26485] set statement_timeout = '1200000'
-- [26485] [26485] Running set statement_timeout = '1200000'
-- [26485] Success.
-- [26485] set application_name to 'ColumnEncodingUtility-v.9.3.2'
-- [26485] [26485] Running set application_name to 'ColumnEncodingUtility-v.9.3.2'
-- [26485] Success.
-- [26485] Connected to dms1.cyirsgk0j39u.ap-northeast-1.redshift.amazonaws.com:5439:dms as root
-- [26485] Analyzing Table 'redshift' for Columnar Encoding Optimisations with 1 Threads...
-- [26485] Recommended encoding changes will be applied automatically...
/* [26485]
select trim(a.name) as table, b.mbytes, a.rows, decode(pgc.reldiststyle,0,'EVEN',1,'KEY',8,'ALL') dist_style, TRIM(pgu.usename) "owner", pgd.description
from (select db_id, id, name, sum(rows) as rows from stv_tbl_perm a group by db_id, id, name) as a
join pg_class as pgc on pgc.oid = a.id
left outer join pg_description pgd ON pgd.objoid = pgc.oid
join pg_namespace as pgn on pgn.oid = pgc.relnamespace
join pg_user pgu on pgu.usesysid = pgc.relowner
join (select tbl, count(*) as mbytes
from stv_blocklist group by tbl) b on a.id=b.tbl
and pgn.nspname::text ~ 'mydb' and pgc.relname in ('redshift')        
        
*/

-- [26485] Analyzing 1 table(s) which contain allocated data blocks
-- [26485] [u'redshift', 42, 1000000, u'EVEN', u'root', None]
/* [26485]
select /* getting count of raw columns in table */ count(9) count_raw_columns
      from pg_table_def 
      where schemaname = 'redshift'
        and lower(encoding) in ('raw','none') 
        and sortkey != 1        
        and tablename = '42'

*/

-- [26485] Table redshift.42 does not require encoding optimisation
-- [26485] Performed modification of 0 tables

And you can get the snapshots of the table info in redshift from the following link:
Result of running "analyze compression"
https://s3.amazonaws.com/junyu-virginia/redshift-analyze.png
Result of table size
https://s3.amazonaws.com/junyu-virginia/redshift-size.png
Result of show create table
https://s3.amazonaws.com/junyu-virginia/redshift-show.png

Feel free to tell me if you need any other info.

**Comment by IanMeyers** [comment]
Ok I see the issue. Will fix shortly.

**Comment by IanMeyers** [comment]
Fixed in https://github.com/awslabs/amazon-redshift-utils/commit/71681dc87b90d4129da1a9233a90ba5509b86563. Sorry about that.

**Comment by iwasnobody** [comment]
It works. Appreciate!
