### ISSUE TITLE
Comments inconsistent with the script creating unnecessary confusion

### ISSUE THREAD

**Issue by ksathya** [awslabs/amazon-redshift-utils#276]
The comments on the following lines are all wrong and hence super confusing . It needs to be revised and corrected.  

https://github.com/awslabs/amazon-redshift-utils/blob/master/src/AnalyzeVacuumUtility/lib/analyze_vacuum.py#L215
https://github.com/awslabs/amazon-redshift-utils/blob/master/src/AnalyzeVacuumUtility/lib/analyze_vacuum.py#L234
https://github.com/awslabs/amazon-redshift-utils/blob/master/src/AnalyzeVacuumUtility/lib/analyze_vacuum.py#L300

**Comment by IanMeyers** [comment]
Fixed in https://github.com/awslabs/amazon-redshift-utils/commit/3fe6e40be318e3a7abe35b726d20cd9a2355a13a
