### ISSUE TITLE
Column Encoding Utility - Interleaved sortkeys

### ISSUE THREAD

**Issue by eliran-lightricks** [awslabs/amazon-redshift-utils#277]
I've noticed the column encoding utility chooses the encode all the columns of an interleaved sort key except the first one.
According to the documentation, sort keys are by default RAW encoded.

I've omitted a few columns, but they are not part of the sortkey.
```
-- [97877] Analyzing Table 'public.events'
-- [97877] Column Encoding will be modified for public.events
-- [97877] No encoding modifications run for public.events
begin;
lock table public."events";
create table public."events_$mig"(
"event_id" varchar(36)  NOT NULL encode zstd 
,"device_timestamp" timestamp   NOT NULL encode RAW 
,"id" varchar(36)  NOT NULL encode zstd DISTKEY
,"device_info" varchar(36)  NOT NULL encode zstd 
,"another_timestamp" timestamp   NOT NULL encode zstd 
,"video_session_id" varchar(36)   encode zstd 
)
 INTERLEAVED SORTKEY(device_timestamp,id,another_timestamp,video_session_id)
 ;
```
Is that an expected behaviour or a bug in the utility?

**Comment by IanMeyers** [comment]
Hello - yes, this is expected behaviour.

**Comment by jasperchan** [comment]
@IanMeyers Does that mean it is fine to apply compression to interleaved sort keys? The documentation on this seems very sparse. Given that interleaved sort "treats all columns equally", what is the difference between the 1st and nth column from a compression/performance basis?

**Comment by strangemonad-faire** [comment]
See this great blog post which describes the process in detail https://chartio.com/blog/interleaved-sort-keys-part-2/

From that description, we can infer that an interleaved sort key yields a new bitint (64bit) value computed from the column values specified for the interleaved sort key. This implies that the columns can be compressed.
