### ISSUE TITLE
cannot change data type of view column "ddl" on creating new v_generate_tbl_ddl

### ISSUE THREAD

**Issue by ovidiu-eremia** [awslabs/amazon-redshift-utils#282]
Hi,

I get cannot change data type of view column "ddl" when trying to create this view on Redshift:
https://github.com/awslabs/amazon-redshift-utils/blob/master/src/AdminViews/v_generate_tbl_ddl.sql

Please help!
Thanks,
Ovidiu

**Comment by joeharris76** [comment]
I don't understand your issue, can you clarify? What SQL did you try to run? What error did you receive?

**Comment by enkeboll** [comment]
I got this error once when I was trying to recreate this view.  Was fixed by dropping the view first and then creating the view, rather than replacing.

**Comment by joeharris76** [comment]
OK, thanks.
