### ISSUE TITLE
ColumnEncodingUtility doesn't set grants correctly

### ISSUE THREAD

**Issue by kevinviraudDH** [awslabs/amazon-redshift-utils#291]
Hi,

There is multiple issues with the way the grants are set after encoding a table.

One being a **major** one :  it seems that if a user has "select" access he is then given all other permissions (delete, insert, references, update).
I believe the mistake is line 279 : **"if grant[1] == True:**". The index should probably be dynamic and not set to 1 which seems to correspond to the "HAS_TABLE_PRIVILEGE" of the select.

The second one is mostly inconvenient if like us, grants are managed by group.
The script actually set back grants on a user level which kind of breaks permissions handling at an higher level. It would be nice if it would reproduce the actual permissions by matching what this query gives somehow : 
`SELECT  table_schema,
			table_name,
			privilege_type,
			g.groname is not null  as is_group,
			grantee
FROM information_schema.table_privileges tp
LEFT JOIN pg_group g ON  (g.groname = tp.grantee)
limit 100
`

**Comment by IanMeyers** [comment]
The first (ridiculous) issue is fixed in https://github.com/awslabs/amazon-redshift-utils/commit/b00010bf5e887d40bf6eb433925449b74ae4b70c. Lemme look at the group thing next.

**Comment by IanMeyers** [comment]
The second should now be fixed in https://github.com/awslabs/amazon-redshift-utils/commit/b3623df4d4ddfea2fb37b58849de8df8efd4eb84

**Comment by kevinviraudDH** [comment]
All fixed thanks !

**Comment by kevinviraudDH** [comment]
I need to reopen the issue because of : 
**"The view table_privileges identifies all privileges granted on tables or views to the current user or by the current user"**.

So if a table was created by another user than the one used to execute the script. Then it won't be caught. 

Trying to find what the right query should be..

**Comment by kevinviraudDH** [comment]
`WITH priviledge AS 
(
	 SELECT 'SELECT'::varchar(10) as "grant"
	 UNION ALL 
	 SELECT 'DELETE'::varchar(10)
	 UNION ALL 
	 SELECT 'INSERT'::varchar(10)
	 UNION ALL 
	 SELECT 'UPDATE'::varchar(10)
	 UNION ALL 
	 SELECT 'REFERENCES'::varchar(10)
),
usr AS
(
	SELECT usesysid, 0 as grosysid, usename, false as is_group
	FROM pg_user
	WHERE usename != 'rdsdb'
	UNION ALL 
	SELECT 0, grosysid, groname, true
	FROM pg_group
)
SELECT nc.nspname AS table_schema, 
            c.relname AS  table_name, 
            priviledge."grant" AS privilege_type,
	    usr.is_group,
            usr.usename AS grantee
FROM pg_class c
JOIN pg_namespace nc ON (c.relnamespace = nc.oid)
CROSS JOIN usr 
CROSS JOIN priviledge 	   
CROSS JOIN pg_user 
WHERE  (c.relkind = 'r'::"char" OR c.relkind = 'v'::"char")
AND pg_user.usename  != 'rdsdb'
AND aclcontains(c.relacl, makeaclitem(usr.usesysid, usr.grosysid, pg_user.usesysid, priviledge."grant", false))
;`

Should do the trick. It's basically the same as table_privileges but removes the check on current user and contains minor adjustments.

**Comment by kevinviraudDH** [comment]
Hi, @IanMeyers 
Do you think that would be reasonable to use that query  ? It became difficult here to maintain tables which doesn't belong to our main user due to the limitation of table_privileges.

**Comment by IanMeyers** [comment]
Yep - if that fixes the issue, happy to take a PR.

**Comment by saeedma8** [comment]
[Amazon Redshift Column Encoding Utility](https://github.com/awslabs/amazon-redshift-utils/tree/master/src/ColumnEncodingUtility#amazon-redshift-column-encoding-utility) is now deprecated. Instead, please use Redshift's Automatic Table Optimization features through:

```
ALTER TABLE table_name ALTER SORTKEY AUTO;
ALTER TABLE table_name ALTER DISTSTYLE AUTO;
```

https://docs.aws.amazon.com/redshift/latest/dg/t_Creating_tables.html
