### ISSUE TITLE
ColumnEncodingUtility : add buffer option for column resize

### ISSUE THREAD

**Issue by kevinviraudDH** [awslabs/amazon-redshift-utils#292]
Automatic resize of varchar columns is something we are very interested in.

However we think it is too restrictive as it is as it resizes to the current MAX octet_length of the column. It might very quickly make some ETL jobs fail with a "**Value too long for character type**" error. 

It would be nice to have a "buffer" option (maybe in percent) so the column would be securely resized for future loads such as for example : 

_MAX(octet_lenght(col)) = 32
Original size = 4000
buffer_size = 20%_ 

gives : 

**new size** = 32 x 1.20 = 38 (truncated to the integer).

There should however be a check on new size as well to take into account the MAX of 65535 for a varchar column so the scripts doesn't fail.

**Comment by IanMeyers** [comment]
Do you think this only applies to varchar type, or also to numerics?

**Comment by IanMeyers** [comment]
I've assumed that we would want to support this variability calculation in all types to be reduced in size. Please have a go with version .9.3.4 from https://github.com/awslabs/amazon-redshift-utils/commit/1673b3004bca3f74221426ec556f79cdec18c5e2

**Comment by kevinviraudDH** [comment]
I assume too.

What happens for varchar if new_column_len  is higher than 65535 ? Does Redshift take MAX as default value  anyway or does it fail ?

Will the COL_LENGTH_EXPANSION_BUFFER be parameterizable as some point ?

**Comment by kevinviraudDH** [comment]
Super thanks !

**Comment by saeedma8** [comment]
[Amazon Redshift Column Encoding Utility](https://github.com/awslabs/amazon-redshift-utils/tree/master/src/ColumnEncodingUtility#amazon-redshift-column-encoding-utility) is now deprecated. Instead, please use Redshift's Automatic Table Optimization features through:

```
ALTER TABLE table_name ALTER SORTKEY AUTO;
ALTER TABLE table_name ALTER DISTSTYLE AUTO;
```

https://docs.aws.amazon.com/redshift/latest/dg/t_Creating_tables.html
