### ISSUE TITLE
ColumnEncodingUtility : value of analyze_col_width is ignored

### ISSUE THREAD

**Issue by kevinviraudDH** [awslabs/amazon-redshift-utils#293]
analyze_col_width  option seems to currently act only as a flag.

However the documentation of the Redshift automation folder states that : 
_"analyze_col_width": "Width of varchar columns to be optimised during encoding analysis (default 1)",_

As far as I understand it means it should analyze columns with an equal or bigger size than analyze_col_width. 

Line **556** (if curr_col_length > 255) seems to suggest the value is hardcoded and analyze_col_width  ignored.

**Comment by IanMeyers** [comment]
Right you are - documentation has been updated in https://github.com/awslabs/amazon-redshift-utils/commit/4cd2745c4ed72a98529ee57831a4b69e7e4bd22a
