### ISSUE TITLE
Cron Allowed Pattern Expressions for Deploy.yaml in RedshiftAutomation conflict with 

### ISSUE THREAD

**Issue by austent89** [awslabs/amazon-redshift-utils#295]
``
AllowedPattern: ^([0-59]|\*|\,|\-|\/) ([0-59]|\*|\,|\-|\/) ([0-59]|\*|\,|\-|\/|\?|L|W) ([0-59]|\*|\,|\-|\/) ([0-59]|\*|\,|\-|\/|\?|L|\#) ([0-59]|\*|\,|\-|\/)$
``

Valid cron expressions as defined by https://docs.aws.amazon.com/lambda/latest/dg/tutorial-scheduled-events-schedule-expressions.html do not pass validation

5 17 * * SAT * fails

The pattern should be updated to reflect the latest scheduled events expressions or better documentation should be provided to indicate why the allowed expressions pattern differs.

**Comment by austent89** [comment]
5 17 * * 6L * is the correct format

**Comment by gorros** [comment]
Why is this one closed? I am trying this patterns and they fail:
```
0 14 ? * SAT *
0 22 ? * SUN * 
0 14 ? * TUE,THU *
0 14 ? * SAT *
```
Also with numbers instead of weekday string.
What am I doing wrong?

**Comment by austent89** [comment]
I've reopened the issue since this is still an issue with the existing templates.

**Comment by gorros** [comment]
I've already opened it, and I know why this happens:
https://github.com/awslabs/amazon-redshift-utils/issues/335
