### ISSUE TITLE
Missing /src/WorkloadManagementScheduler/lib directory

### ISSUE THREAD

**Issue by O1moore** [awslabs/amazon-redshift-utils#296]
The script /src/RedshiftAutomation/build.sh includes this on line 49:

cp -R ../WorkloadManagementScheduler/lib lib/WorkloadManagementScheduler

However, this directory is not currently present at:
https://github.com/awslabs/amazon-redshift-utils/tree/master/src/WorkloadManagementScheduler

This is causing import errors in the lambda function when created:
"No module named wlm_scheduler"

**Comment by IanMeyers** [comment]
Hello,

Can you provide a full stack trace of the error you observe? There should be no reason to rebuild the project unless you've made changes, and in this case you need to ensure that you have the entire github repo synced.

Thx,

Ian

**Comment by timjell** [comment]
Closing as no longer relevant/no further information provided by requester. Additionaly the WorkloadManagementScheduler is currently in EOL status and will not be actively maintained. Refer to the AutoWLM documentation for the preferred methods.
