### ISSUE TITLE
Script failing even when --ignore-errors set to TRUE

### ISSUE THREAD

**Issue by mlevit** [awslabs/amazon-redshift-utils#301]
When the script hits errors such as "Vacuum column limit exceeded" the script stops and does not proceed. See attached logs.

[error_log.txt](https://github.com/awslabs/amazon-redshift-utils/files/1936224/error_log.txt)

**Comment by IanMeyers** [comment]
Will look into this later today.

**Comment by IanMeyers** [comment]
This should be fixed in https://github.com/awslabs/amazon-redshift-utils/commit/0e00dceec0e2b69b7687bd66d91576c5bb7a399f

**Comment by mlevit** [comment]
@IanMeyers doesn't look like the change made any difference. My own workaround was to comment out the "raise" line on line 162.

**Comment by IanMeyers** [comment]
You are correct. Apologies - please try after syncing to https://github.com/awslabs/amazon-redshift-utils/commit/b49f0183c345017b73f70dcfbb61cf9129316d30

**Comment by saeedma8** [comment]
Please let us know if the issue still persists. Thank you.
