### ISSUE TITLE
--report-file argument missing from analyze-schema-compression.py but present in README documentation

### ISSUE THREAD

**Issue by mlevit** [awslabs/amazon-redshift-utils#305]

**Comment by sarah-johnson** [comment]
I just saw this issue, but I submitted a fix for this yesterday https://github.com/awslabs/amazon-redshift-utils/pull/314

**Comment by saeedma8** [comment]
[Amazon Redshift Column Encoding Utility](https://github.com/awslabs/amazon-redshift-utils/tree/master/src/ColumnEncodingUtility#amazon-redshift-column-encoding-utility) is now deprecated. Instead, please use Redshift's Automatic Table Optimization features through:

```
ALTER TABLE table_name ALTER SORTKEY AUTO;
ALTER TABLE table_name ALTER DISTSTYLE AUTO;
```

https://docs.aws.amazon.com/redshift/latest/dg/t_Creating_tables.html
