### ISSUE TITLE
Are Lambda limitations going to be a problem?

### ISSUE THREAD

**Issue by farshidz** [awslabs/amazon-redshift-utils#322]
When I run this tool manually to VCUUM and ANALYZE a database, it usually takes much longer than the 300 second limit of Lambda. Does that mean the [Lambda automation method](https://github.com/awslabs/amazon-redshift-utils/tree/master/src/RedshiftAutomation) is not going to work for me?

**Comment by IanMeyers** [comment]
Hello - yes, in that case I would advise you use the Redshift Automation utility and schedule the `ra` utility from cron on a host.

**Comment by farshidz** [comment]
Thanks!
