### ISSUE TITLE
UnloadCopyUtility: Allow option to specify statement_timeout

### ISSUE THREAD

**Issue by dmohns** [awslabs/amazon-redshift-utils#326]
**Background:** Running UnloadCopyUtility to migrate big database tables fails after 20 minutes with 
```
WARNING:root:ERROR:  Query (71361) cancelled on user's request
```

It looks like `statement_timeout` is currently hardcoded in 
https://github.com/awslabs/amazon-redshift-utils/blob/master/src/UnloadCopyUtility/util/redshift_cluster.py#L15
without any option to adapt it.

**Issue:** As a user, I want to be able to set and adapt statement_timeout parameter according to my problem. Be it via ENV variable, config.json or cmd line parameter.

**Comment by timjell** [comment]
Driver has been moved to the recently released redshift_connector. Timeout is not hard coded any longer and the connection will not be closed while the unload is running.
