### ISSUE TITLE
UnloadCopyUtility: NULL strings are converted to empty strings

### ISSUE THREAD

**Issue by dmohns** [awslabs/amazon-redshift-utils#327]
**Problem:**
When migrating tables with UnloadCopyUtility all `NULL` strings are converted to empty strings `''`. 

**Comment:**
Root cause seems to be default behaviour of `UNLOAD`. One option to circumvent this problem might be setting `null as '\\\N'` for `UNLOAD` job in
https://github.com/awslabs/amazon-redshift-utils/blob/master/src/UnloadCopyUtility/util/resources.py#L273

**Comment by timjell** [comment]
Current code has the NULL defaulted a string value for both the UNLOAD and COPY

`null as 'NULL_STRING__'`

If there is a specific need to change this, then update as required for your circumstances.
