### ISSUE TITLE
V_GENERATE_TBL_DDL creates wrong ddl

### ISSUE THREAD

**Issue by saiteja05** [awslabs/amazon-redshift-utils#334]
CREATE TABLE IF NOT EXISTS public.duplicaterows(	id INTEGER   ENCODE lzo	,name VARCHAR(20)   ENCODE lzo)DISTSTYLE KEYDISTKEY (id);

 instead of
 CREATE TABLE IF NOT EXISTS public.duplicaterows(	id INTEGER   ENCODE lzo	,name VARCHAR(20)   ENCODE lzo)DISTSTYLE KEY DISTKEY (id);

generated by V_GENERATE_TBL_DDL.sql
 encountered a similar spacing issue in #333

**Comment by IanMeyers** [comment]
ea69d1d fixes this one

**Comment by saiteja05** [comment]
thanks IAN :)
