### ISSUE TITLE
Cron validation error.

### ISSUE THREAD

**Issue by gorros** [awslabs/amazon-redshift-utils#335]
I am trying this patterns and they fail:

0 14 ? * SAT *
0 22 ? * SUN * 
0 14 ? * TUE,THU *
0 14 ? * SAT *

Also with numbers instead of weekday string.
What am I doing wrong?

**Comment by gorros** [comment]
This pattern does not match any number larger than 5.
`^([0-59]|\\*|\\,|\\-|\\/) ([0-59]|\\*|\\,|\\-|\\/) ([0-59]|\\*|\\,|\\-|\\/|\\?|L|W) ([0-59]|\\*|\\,|\\-|\\/) ([0-59]|\\*|\\,|\\-|\\/|\\?|L|\\#) ([0-59]|\\*|\\,|\\-|\\/)$`

By coincidence, it works fine for defaults.

**Comment by gorros** [comment]
Valid regex should look like this, 
`([0-5]?[0-9]|\*|\,|\-|\/) ([ 01]?[0-9]|2[0-3]|\*|\,|\-|\/) ([ 012]?[1-9]|3[01]|\*|\,|\-|\/|\?|L|W) ([0]?[1-9]|1[0-2]|\*|\,|\-|\/) ([1-7]|\*|\,|\-|\/|\?|L|\#) (19[7-9][0-9]|2[01][0-9][0-9]|\*|\,|\-|\/)`

this one does not match weekday string, but it works for numbers.

**Comment by IanMeyers** [comment]
Hello - this is a known issue with day names. Will try to spend some time working on a regex that will support this, or alternatively maybe we just drop it and and let SAM validate the input data on validation.

**Comment by gorros** [comment]
This is not just about strings. The issue is that regex is wrong generally. `[0-59]` does not mean numbers from 0 to 59, also it is just repeated for hours days, minutes and so on.

**Comment by IanMeyers** [comment]
Removed pattern validation in 484984a

**Comment by gorros** [comment]
@IanMeyers I noticed that now there are new fields for WLM. But I did not find anything in the readme about that.
