### ISSUE TITLE
The  v_generate_view_ddl does not work  for late-binding views

### ISSUE THREAD

**Issue by lukeligae** [awslabs/amazon-redshift-utils#340]
There is a bug in the  v_generate_view_ddl.sql. It does not work  for late-binding views. It produces a extra "CREATE OR REPLACE VIEW [schema.view] AS". For example:, it will generate the below wrong DDL.

--DROP VIEW  cdwds.cdw_d_prod_v ;
CREATE OR REPLACE VIEW cdwds.cdw_d_prod_v ASCREATE OR REPLACE VIEW CDWDS.CDW_D_PROD_V AS SELECT * FROM CDW.D_PROD with no schema binding;

It work fine for regular views. 

Luke

**Comment by alexlsts** [comment]
Hello lukeli@,
I have tested a new version for the view you have mentioned and it is working now.

--Before
tickit=# select * from admin.v_generate_view_ddl where viewname = 'vw_s3_view';
 schemaname |  viewname  |                                                    ddl                                                    
------------+------------+-----------------------------------------------------------------------------------------------------------
 public     | vw_s3_view | --DROP VIEW public.vw_s3_view;                                                                           +
            |            | CREATE OR REPLACE VIEW public.vw_s3_view AS                                                              +
            |            | create or replace view vw_s3_view as select * from spectrum.account_registrations with no schema binding;
(1 row)

--New version
tickit=# select * from admin.v_generate_view_ddl_new where viewname = 'vw_s3_view';
 schemaname |  viewname  |                                                    ddl                                                    
------------+------------+-----------------------------------------------------------------------------------------------------------
 public     | vw_s3_view | --DROP VIEW public.vw_s3_view;                                                                           +
            |            | create or replace view vw_s3_view as select * from spectrum.account_registrations with no schema binding;
(1 row)

Could you please test the version mentioned in the following link and let me know if it works for you?

https://github.com/alexlsts/amazon-redshift-utils/blob/master/src/AdminViews/v_generate_view_ddl.sql

**Comment by jake-barry** [comment]
Hi @alexlsts 

If you want the DDL to be complete, I think that you need to append 'with no schema binding' to the end of the create statement.

Other than that, this seems to work.

**Comment by alexlsts** [comment]
Hello @jake-barry,
If you execute this view you will see the following output:

tickit=# select * from admin.v_generate_view_ddl where viewname = 'vw_s3_view'; 
 schemaname |  viewname  |                                                    ddl                                                    
------------+------------+-----------------------------------------------------------------------------------------------------------
 public     | vw_s3_view | --DROP VIEW public.vw_s3_view;                                                                           +
            |            | create or replace view vw_s3_view as select * from spectrum.data with no schema binding;
(1 row)

The COALESCE(pg_get_viewdef(c.oid, TRUE), '') have already included the "with no schema binding" for late binding.

**Comment by timjell** [comment]
Closed as code merged
