### ISSUE TITLE
Template validation error: Parameter 'S3ConfigPath' must match pattern ^s3:\/\/([A-z\-]+)\/(.*)$

### ISSUE THREAD

**Issue by llundin** [awslabs/amazon-redshift-utils#347]
S3ConfigPath evaluates false for buckets containing number [0-9], ie. `s3://bucket1/myconf.json`

**Comment by IanMeyers** [comment]
Can you help me know in which file this is an issue - quite a few config files in this repo! Thanks.

Ian

**Comment by gaganawhad** [comment]
@IanMeyers Similar to the above, I had trouble with the allowed pattern in s3 bucket names as well. 

I am not sure it's a good practice, but bucket names have periods in them, and apparently, that's valid, but the Allowed pattern in configuration files doesn't validate it. 

> Bucket names must be a series of one or more labels. Adjacent labels are separated by a single period (.). Bucket names can contain lowercase letters, numbers, and hyphens. Each label must start and end with a lowercase letter or a number.

> 
https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html#bucketnamingrules


There are 4 places where this pattern exists: 

1. https://github.com/awslabs/amazon-redshift-utils/blob/master/src/RedshiftAutomation/deploy.yaml#L50
2. https://github.com/awslabs/amazon-redshift-utils/blob/master/src/RedshiftAutomation/deploy.yaml#L93
3. https://github.com/awslabs/amazon-redshift-utils/blob/master/src/RedshiftAutomation/deploy-function-and-schedule.yaml#L27
4. https://github.com/awslabs/amazon-redshift-utils/blob/master/src/RedshiftAutomation/deploy-schedule.yaml#L22

I did the following change for periods to work, but I am not sure that's watertight: 

```
-    AllowedPattern: ^s3:\/\/([A-z\-]+)\/(.*)$
+    AllowedPattern: ^s3:\/\/([A-z\-\.]+)\/(.*)$
```

**Comment by gaganawhad** [comment]
May be the regex needs to be as sophisticated as this: https://stackoverflow.com/questions/50480924/regex-for-s3-bucket-name

Hope that helps. May be an easier change would be to remove the validation?
