### ISSUE TITLE
Load/copy multiple tables with wrapper script

### ISSUE THREAD

**Issue by hobbsh** [awslabs/amazon-redshift-utils#350]
Hi,

I wrote a wrapper to unload/copy multiple tables at once - it's far from polished though. What do you think about including it in this repo? 

https://gist.github.com/hobbsh/9bd6eb5dcf5f2a687ae7361d92ff321e

My use case for this was migrating from an unencrypted to an encrypted redshift cluster.

**Comment by IanMeyers** [comment]
As a choosing beggar I'd like to see us add support for a configuration of table names as an array in the core utility. Barring that, i think your script is a fine addition - can you submit a pull request with the file in src/UnloadCopyUtility?

**Comment by hobbsh** [comment]
I think supporting a list of tables would be awesome, I look forward to it. I'll get a PR out today hopefully. Thanks!

**Comment by timjell** [comment]
The unload copy utility includes the ability to have multiple tables defined in the configuration file. Closing this.
