### ISSUE TITLE
analyze-schema-compression can swap sortkeys in the order by clause

### ISSUE THREAD

**Issue by davehowell** [awslabs/amazon-redshift-utils#352]
For example, if this is the existing table
```
  CREATE TABLE public.student_task"(
     "id" integer
    ,"task_id" integer
    ,"student_id" integer
  )
```

And you provide this parameter
--new-sort-keys student_id,task_id

Then the sortkey clause will be
`sortkey(student_id,task_id)`

and the order by clause will be swapped:
... `order by task_id, student_id`

This doesn't break things, but will create a large amount of work for vacuum. My understanding is that redshift will insert new records into an "unsorted" sector, but if the data is already sorted then vacuuming is trivial. 

There are a few different data structures related to sort keys used in the code for various purposes. There is one `table_sortkeys` where its primary purpose is to check that provided sortkeys actually exist in the table, and it shouldn't be used for building the `order by` clause. 

The quickest fix for this is to use `new_sortkey_arr` to build the order by.

I would submit a PR but I've made a ton of changes to optimize for the "specify table name" use case, including adding the option to provide a new-dist-style. Perhaps you want to cherry pick some hunks from that if helpful?

**Comment by IanMeyers** [comment]
Fixed in 9d130b3

**Comment by RSiferd2** [comment]
@IanMeyers ,

In the above fix, Line `785` for me is an empty array, which is causing an error. Did you mean to call `len` on `new_sortkey_arr` instead in line `784`?

**Comment by RSiferd2** [comment]
@davehowell ,

No worries at all, is easy to work around regardless. I've tried that snippet you suggested above, and that seems to work just fine.
