### ISSUE TITLE
[Question] KeyError: 'snapshotNew' in TablePersistence

### ISSUE THREAD

**Issue by emirot** [awslabs/amazon-redshift-utils#356]
If I understand correctly, this variable snapshot_new in (https://github.com/awslabs/amazon-redshift-utils/blob/master/src/SystemTablePersistence/snapshot_system_stats.py#L86)[https://github.com/awslabs/amazon-redshift-utils/blob/master/src/SystemTablePersistence/snapshot_system_stats.py#L86]
comes from https://github.com/awslabs/amazon-redshift-utils/blob/master/src/SystemTablePersistence/lib/history_table_config.json but it's not defined there. 

So I get ```Traceback (most recent call last):
  File "./ra", line 116, in <module>
    cli(args.utility, args.config, use_region)
  File "./ra", line 96, in cli
    snapshot_system_stats.snapshot([config, os.environ])
  File "./lib/SystemTablePersistence/snapshot_system_stats.py", line 252, in snapshot
    insert_rowcounts = snapshot_system_tables(cursor, conn, table_config)
  File "./lib/SystemTablePersistence/snapshot_system_stats.py", line 87, in snapshot_system_tables
    snapshot_new = t['snapshotNew']
KeyError: 'snapshotNew'``` 
Should it be something we have to define manually ?

**Comment by emirot** [comment]
@IanMeyers any idea ?

**Comment by IanMeyers** [comment]
Yeah - sorry. Looks like the merge that added this was broken and didn't include the config file changes. Looking...

**Comment by emirot** [comment]
Awesome thanks !

**Comment by IanMeyers** [comment]
Phew - recovered from the excellent 'export function' feature of Lambda as the original file had gotten munched during change of laptop. f278368 fixes it!

**Comment by emirot** [comment]
Thanks @IanMeyers for looking it, I'm glad to see this change f278368 coming soon.

**Comment by emirot** [comment]
@IanMeyers please let me know when you push this file, closing that issue.

**Comment by IanMeyers** [comment]
The file was updated at https://github.com/awslabs/amazon-redshift-utils/blob/master/src/SystemTablePersistence/lib/history_table_config.json

**Comment by emirot** [comment]
I can't see the snapshotNew key inside and last updated time of this file was April 6.

**Comment by IanMeyers** [comment]
Something really broken with my git setup. Have updated in the web site.
