### ISSUE TITLE
[Question] Deleting users thanks to a CLI tool

### ISSUE THREAD

**Issue by emirot** [awslabs/amazon-redshift-utils#368]
I was wondering if it could be a great idea to have a command line tool to delete users.
It looks to be a common problem and I haven't found a clear solution since in redshift there is no 
'REASSIGN' instruction.

Strategies found : 
https://dba.stackexchange.com/questions/143938/drop-user-in-redshift-which-has-privilege-on-some-object

**Comment by IanMeyers** [comment]
I think this is a good idea.

**Comment by emirot** [comment]
Revoking what I'm seeing here doesn't seem to work : 
```SELECT * FROM admin.v_get_obj_priv_by_user``` does someone experienced that ? 
I have almost run the same commands as described here : 
https://forums.aws.amazon.com/message.jspa?messageID=468047

**Comment by adedotua** [comment]
@emirot this view https://github.com/adedotua/amazon-redshift-utils/blob/master/src/AdminViews/v_generate_user_grant_revoke_ddl.sql was created for this purpose. It should be used in conjunction with https://github.com/adedotua/amazon-redshift-utils/blob/master/src/AdminViews/v_find_dropuser_objs.sql. The first view finds all the grants that should be revoked and the second finds all the objects owned by the user.

**Comment by adedotua** [comment]
The steps to follow are described here https://aws.amazon.com/premiumsupport/knowledge-center/redshift-user-cannot-be-dropped/

**Comment by emirot** [comment]
Thanks @adedotua ! It doesn't feel right to go on support just to delete a user. 
What the best practice for creating or deleting users, using IAM instead ?

**Comment by adedotua** [comment]
Connecting to the cluster and creating or deleting users is still best practice. IAM is more for ease of connecting to the database via SAML but does not currently offer a way to delete users from the database.
