### ISSUE TITLE
Vacuum tables flagged by alert

### ISSUE THREAD

**Issue by tanjabrzak** [awslabs/amazon-redshift-utils#377]
Query for vacuum candidates flagged by alert will not return any rows because of this condition

https://github.com/awslabs/amazon-redshift-utils/blob/master/src/AnalyzeVacuumUtility/lib/analyze_vacuum.py#L264

That regexp will be always 0.

```
select regexp_instr('Run the VACUUM command to reclaim deleted space','.*VACUUM.reclaim deleted.');
 regexp_instr
--------------
            0
(1 row)
```

Condition should be rewritten to something like this

```
select regexp_instr('Run the VACUUM command to reclaim deleted space','.*VACUUM command to reclaim deleted.');
 regexp_instr
--------------
            1
(1 row)
```

**Comment by timjell** [comment]
Closing as fixed due to commit referenced above
