### ISSUE TITLE
Exception when running encoding

### ISSUE THREAD

**Issue by stylehaullong** [awslabs/amazon-redshift-utils#388]
- [26352] Analyzing Table 'bill_trans_test' for Columnar Encoding Optimisations with 1 Threads...
-- [26352] Recommended encoding changes will be applied automatically...
-- [26352] Analyzing 1 table(s) which contain allocated data blocks
-- [26352] Table merlin.bill_trans_test contains 0 unoptimised columns
-- [26352] Using Force Override Option
-- [26352] Analyzing Table 'merlin.bill_trans_test'
Exception 'process_timeperiod' during analysis of bill_trans_test
Traceback (most recent call last):
  File "analyze-schema-compression.py", line 640, in analyze
    row_sortkey = descr[col][4]
KeyError: 'process_timeperiod'

Error in worker thread: return code 1. Exiting.

Is this related to the safewords issue?

**Comment by stylehaullong** [comment]
Hi All,

Just wanted to report back this is due to the cluster not having anything in the information_schema.schemata.

Maybe we can just take the schema name if they use the --schema param or look up the table if they use --table param and use the schema that comes back from that. 

Wanted to ask you all about possibilities of adding dependency checking and relinking if you think that's possible, thanks!

**Comment by IanMeyers** [comment]
The line that has the issue doesn't actually access information_schema.schemata, but is based on the query in get_table_desc() using pg_table_def and pg_attribute. Can you give me a bit more information about this table and setup? I can't see why we'd get a column in one case and not in another.

**Comment by stylehaullong** [comment]
Hi Ian,

What I found out is this is due to the user (--db_user) not being the owner of the object/schema. Which then in turns does set the schema into the path(line 200 aws_utils.set_search_paths(conn, schema_name, target_schema). 
Then when the get_table_desc() function is ran, pg_table_def, and pg_attribute actually return nothing

**Comment by IanMeyers** [comment]
Got it. Looking.
