### ISSUE TITLE
S3 regex

### ISSUE THREAD

**Issue by ibrahim-xaheer** [awslabs/amazon-redshift-utils#391]
The Regex for the "AllowedPattern" for the parameters "S3ConfigPath" and "WlmSchedulerConfigLocation" don't let you provide a bucket name that contains numbers.

For example:
s3://cf-templates-1ud54sbq8a-eu-west-1/config.json should be a valid value, but it gives the error of parameter constraint as the bucket name contains numbers.

**Comment by IanMeyers** [comment]
Should be fixed now.
