### ISSUE TITLE
analyze-schema-compression not rejecting invalid arguments

### ISSUE THREAD

**Issue by dboobis** [awslabs/amazon-redshift-utils#399]
In the documentation it states to use the argument --ssl-option to change whether or not to use SSL. However, in the source the argument is --ssl, so going by the documentation it will fail to connect and hang indefinitely. Using the argument --ssl allows it to parse and process as expected.

Please change either the documentation or the source so SSL users don't get stuck on this.

**Comment by IanMeyers** [comment]
Hmm - I'm confused. If you look [at the source that parses command line args](https://github.com/awslabs/amazon-redshift-utils/blob/5b4f8e9253981454d2305e322d2664d592306c75/src/ColumnEncodingUtility/analyze-schema-compression.py#L1217) you can see that it uses the string value 'ssl-option'. Where are you seeing that the source argument is '--ssl'?

**Comment by dboobis** [comment]
That is odd, it definitely wasn't parsing --ssl-option but did --ssl. According to that source it should have returned "Unsupported Argument".

[Here is a screenshot demonstrating this](https://i.imgur.com/d4FyLe7.png)

**Comment by IanMeyers** [comment]
Got it. AFAIK you get the correct behaviour for SSL secured connections with the argument. This bug is down to the fact that invalid args aren't failing like they should. I'll look into this.

**Comment by saeedma8** [comment]
[Amazon Redshift Column Encoding Utility](https://github.com/awslabs/amazon-redshift-utils/tree/master/src/ColumnEncodingUtility#amazon-redshift-column-encoding-utility) is now deprecated. Instead, please use Redshift's Automatic Table Optimization features through:

```
ALTER TABLE table_name ALTER SORTKEY AUTO;
ALTER TABLE table_name ALTER DISTSTYLE AUTO;
```
https://docs.aws.amazon.com/redshift/latest/dg/t_Creating_tables.html
