### ISSUE TITLE
Dockerfile entrypoint. 

### ISSUE THREAD

**Issue by ReptilianBrain** [awslabs/amazon-redshift-utils#413]
According to the README one should be able to start using the utilities right after building the docker images

> You can do this by building the image like so:
> 
> docker build -t amazon-redshift-utils .
> And then executing any one of the 3 following commands (filling in the -e parameters as needed):
> 
> docker run --net host --rm -it -e DB=my-database .... amazon-redshift-utils analyze-vacuum
> docker run --net host --rm -it -e DB=my-database .... amazon-redshift-utils column-encoding
> docker run --net host --rm -it -e CONFIG_FILE=s3://.... amazon-redshift-utils unload-copy

but the entrypoint of the dockerfile was commented out recently to:
`# ENTRYPOINT ["/usr/src/app/bin/entrypoint.sh"]
`
`ENTRYPOINT ["/bin/sh"]` (https://github.com/awslabs/amazon-redshift-utils/commit/4f96d1b96f7acb0c5de35d071113144b459cadea)

Should it be uncommented or maybe the readme updated ?

**Comment by IanMeyers** [comment]
Have removed the commenting out - was clearly for some testing and should not have been done.
