### ISSUE TITLE
Getting Error with  analyze-schema-compression.py ImportError: No module named config_constants

### ISSUE THREAD

**Issue by Barathchander** [awslabs/amazon-redshift-utils#415]
Getting error when i run analyze-schema-compression.py that no module named config_common 

> Traceback (most recent call last):
  File "analyze-schema-compression.py", line 56, in <module>
    import config_constants
ImportError: No module named config_constants

**Comment by Barathchander** [comment]
Thanks for the response. That fixed the issue, but I am getting another one

  File "./analyze-schema-compression.py", line 1262, in <module>
    main(sys.argv)
  File "./analyze-schema-compression.py", line 1255, in main
    result_code = run()
  File "./analyze-schema-compression.py", line 972, in run
    master_conn = get_pg_conn()
  File "./analyze-schema-compression.py", line 194, in get_pg_conn
    aws_utils.set_search_paths(conn, schema_name, target_schema)
AttributeError: 'module' object has no attribute 'set_search_paths'

Should I supply all parameters ? I am supplying only below ones.

./analyze-schema-compression.py --db 'xx' --db-user 'xxxx' --db-pwd 'xxxx'--db-host abcs.kahdkahdkjsadjshdkj.us-east-1.redshift.amazonaws.com --db-port 5439 --analyze-schema 'xxx' --target-schema 'xxx'

**Comment by Barathchander** [comment]
@IanMeyers - i have tried to get different options but could not get over with above step.

**Comment by saeedma8** [comment]
[Amazon Redshift Column Encoding Utility](https://github.com/awslabs/amazon-redshift-utils/tree/master/src/ColumnEncodingUtility#amazon-redshift-column-encoding-utility) is now deprecated. Instead, please use Redshift's Automatic Table Optimization features through:

```
ALTER TABLE table_name ALTER SORTKEY AUTO;
ALTER TABLE table_name ALTER DISTSTYLE AUTO;
```
https://docs.aws.amazon.com/redshift/latest/dg/t_Creating_tables.html
