### ISSUE TITLE
Snapshot Manager Hangs and timeout after 300 seconds

### ISSUE THREAD

**Issue by ksiddiqui79** [awslabs/amazon-redshift-utils#429]
I just deployed SnapshotManager using SAM with following configuration for hourly snapshot.

`{  "snapshotIntervalHours": "1",  "targetResource": "rs-iam-test",  "namespace": "hourly",  "region": "us-east-1",  "snapshotRetentionDays": "7"}`

CloudWatch event is triggering Lambda, but Lambda hangs for 5 mins and timeout after 300 seconds without any message in log.

#### Log messages:
> START RequestId: 9fc47ef4-c6c7-4889-8270-16ad3fc87d54 Version: $LATEST
> 2019-03-19T08:34:38.491Z	9fc47ef4-c6c7-4889-8270-16ad3fc87d54	Configuration Provided:
> {
>     "snapshotIntervalHours": "1",
>     "targetResource": "rs-iam-test",
>     "namespace": "hourly",
>     "region": "us-east-1",
>     "snapshotRetentionDays": "7"
> }
> 2019-03-19T08:34:38.494Z	9fc47ef4-c6c7-4889-8270-16ad3fc87d54	Requesting 
'hourly' Snapshots for rs-iam-test in interval (2019-03-19T07:34:38+00:00 - any)
> END RequestId: 9fc47ef4-c6c7-4889-8270-16ad3fc87d54
> REPORT RequestId: 9fc47ef4-c6c7-4889-8270-16ad3fc87d54	Duration: 300024.39 ms	Billed Duration: 300000 ms Memory Size: 192 MB	Max Memory Used: 38 MB	
> 2019-03-19T08:32:49.163Z 9fc47ef4-c6c7-4889-8270-16ad3fc87d54 Task timed out after 300.02 seconds

I checked and updated IAM policy attached to the role for this Lambda. It has "redshift:*" on all resources. But still no luck.

**Comment by IanMeyers** [comment]
When you see hang type behaviour on Lambda, it tends to be because Lambda cannot egress your VPC so that it can talk to the Redshift API's. Can you please consult https://github.com/awslabs/aws-lambda-redshift-loader/blob/master/Networking.md for more information on how to configure your Lambda function to work with AWS services, and then let us know if you still have an issue?

**Comment by saeedma8** [comment]
[Amazon Redshift Snapshot Manager](https://github.com/awslabs/amazon-redshift-utils/tree/master/src/SnapshotManager#amazon-redshift-snapshot-manager) is now deprecated and you can use the [native Redshift Snapshot Scheduler](https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-snapshots.html#working-with-snapshot-scheduling) instead.
