### ISSUE TITLE
Column Encoding Utility

### ISSUE THREAD

**Issue by rajivchodisetti** [awslabs/amazon-redshift-utils#43]
HI Eric ,

I am using the column encoding utility and is working great but has just 2 missing pieces like , provide couple of extra flags like , apply the grants which exist on the old table to new table and the other one is , if there are any objects (views) depends on the older table , then re-create the same and copy the necessary privileges .

Just add these 2 missing pieces and it will be a complete table migration script

**Comment by rajivchodisetti** [comment]
In addition to the above 2 options , there should be an additional option to provide list of tables as an argument , as of now am baby sitting and re-creating tables one by one and then applying required permissions

**Comment by jklukas** [comment]
Being able to recreate grants was also an important feature for me. My team ended up contributing to the [Redshift sqlalchemy dialect](http://sqlalchemy-redshift.readthedocs.org/en/latest/) to implement some more general-purpose reflection functionality, and we use that in our [shiftmanager suite of admin tools](https://github.com/SimpleFinance/shiftmanager) to perform [migrations](https://shiftmanager.readthedocs.org/en/latest/#schema-reflection-deep-copies-deduping-and-migrations). 

There unfortunately doesn't appear to be any straightforward option (besides `pg_dump`) for recreating the grants. We had to write some logic to parse permissions strings, as captured in https://github.com/SimpleFinance/shiftmanager/blob/master/shiftmanager/privileges.py

I'd love to see some similar logic applied in the column encoding utility.

**Comment by razzakulchowdhury** [comment]
When DDL is generated by this Python script for compressed table it  changes table distribution style  from KEY to EVEN. Seems it’s a big snag! Whereas dist_style = EVEN  hasn’t been changed by the script, it remains as it is.

**Comment by IanMeyers** [comment]
Can you give an example of a table definition where you see this happen? I've not been able to reproduce the issue that you cite on a table with a specified distribution key.

**Comment by IanMeyers** [comment]
Regarding table grants, I've opened https://github.com/awslabs/amazon-redshift-utils/issues/240

**Comment by IanMeyers** [comment]
Regarding multi-table analysis, I've opened https://github.com/awslabs/amazon-redshift-utils/issues/241

**Comment by IanMeyers** [comment]
Fixed in https://github.com/awslabs/amazon-redshift-utils/commit/49d708ee3c171e784f43ac4055c8c5664dcd49ee
