### ISSUE TITLE
Concurrency testing - ScriptRunner

### ISSUE THREAD

**Issue by gmanjunath** [awslabs/amazon-redshift-utils#430]
Hello,

**Bug description:**
I was trying to test concurrency functionality in RS and noticed that there is script (ScriptRunner.sh) which supports this bit. I was trying to testing by running 10 instances of the query. Unfortunately there is a bug in the script, which prevents testing concurrency.

**Reproducing**
This is very easy to reproduce:
1. echo the script under test to file
2. ./ScriptRunner.sh 10 file

Notice that only one instance of the script gets run.

**Fix**
I fixed locally in my docker container. The bug is in line 139. Happy to provide fix as a pull request, please let me know.

Thanks
Manju

**Comment by IanMeyers** [comment]
Happy to take a PR for this - thanks!
