### ISSUE TITLE
Add support for changing static WLM properties with the WorkloadManagementScheduler

### ISSUE THREAD

**Issue by BigDataDaddy** [awslabs/amazon-redshift-utils#438]
The WorkloadManagementScheduler util currently accepts any WLM JSON and applies it dynamically with a Boto modify_cluster_parameter_group call with a 'ApplyType': 'dynamic' parameter.  This call will leave any static WLM properties in a pending reboot state. 

This issue requests that either:
1. The static WLM properties in the supported JSON be made dynamic.
2. That the WorkloadManagementScheduler reboot the cluster afte the modify_cluster_parameter_group Boto call if static WLM properties are present in the JSON.

Alternatively this util could be made more understandable if the current implementation just threw and exception before the modify_cluster_parameter_group Boto call if static WLM properties are present in the JSON.

**Comment by timjell** [comment]
Closing this feature request as Auto WLM is the preferred method of managing workload (https://docs.aws.amazon.com/redshift/latest/dg/automatic-wlm.html). The WLM Scheduler is currently in EOL state
