### ISSUE TITLE
Wrong comment of ColumnEncodingUtility/analyze_schema_compression.py 

### ISSUE THREAD

**Issue by RongQiao** [awslabs/amazon-redshift-utils#440]
Scenario: I choose to only analyze the table (didn't set do-execute arg), but the output file has below info:

-- [4960] No encoding modifications run for <my table name>
begin;
...
commit;
-- [4960] Performed modification of 1 tables

I feel confused about the two [4960] lines, which are conflict to each other. By checking source code, I saw code "comment("Performed modification of %s tables" % modified_tables)" is after analyzing code, but not in any if condition. It seems a bug for me. Can you check this issue?

**Comment by RongQiao** [comment]
In addition, in file https://github.com/awslabs/amazon-redshift-utils/blob/master/src/ColumnEncodingUtility/analyze-schema-compression.py, the function cleanup() missed one statement 'db_connections[key] = None' after the connection was closed.

def cleanup(conn):
    # close all connections and close the output file
    if conn is not None:
        close_conn(conn)

    for key in db_connections:
        if db_connections[key] is not None:
            close_conn(db_connections[key])
            # to add
            db_connections[key] = None

Why does it matter? I am writing my python script to call this utility for multiple tables (every table will call the main() function). In this case, because the python program is in the same PID, so the next call get_pg_conn() will try to reuse the existing connection as it's not None but it has been closed so it doesn't work. I tried to use shell script to call, which doesn't have the issue as every python execution will have its own PID. I don't want to use the list for 'analyze-table' parameter as I may have a lot of tables which is not desired in one call.

**Comment by IanMeyers** [comment]
Understood. Will have a look later this week.

**Comment by saeedma8** [comment]
[Amazon Redshift Column Encoding Utility](https://github.com/awslabs/amazon-redshift-utils/tree/master/src/ColumnEncodingUtility#amazon-redshift-column-encoding-utility) is now deprecated. Instead, please use Redshift's Automatic Table Optimization features through:

```
ALTER TABLE table_name ALTER SORTKEY AUTO;
ALTER TABLE table_name ALTER DISTSTYLE AUTO;
```

https://docs.aws.amazon.com/redshift/latest/dg/t_Creating_tables.html
