### ISSUE TITLE
UnloadAutoPartitions: UNLOAD to Parquet format is not supported

### ISSUE THREAD

**Issue by mbishop-bb** [awslabs/amazon-redshift-utils#463]
Running a test unload on one of our tables yields the error:

`
UNLOAD to Parquet format is not supported
`

I wasn't able to find any Redshift documentation that suggest unloading to Parquet was supported and unsure why aws would publish a utility that uses an unsupported parameter?   Is this something we need to specifically request from support for our cluster or an error in the library?

**Comment by ericfe** [comment]
You are correct, the utility was pushed out a bit too early.
The feature is on beta and should be GA next month.
