### ISSUE TITLE
Support for a partial UnloadCopy of a Redshift Table

### ISSUE THREAD

**Issue by philnielsen** [awslabs/amazon-redshift-utils#466]
I would love the ability to provide a custom [unload_table_stmt](https://github.com/awslabs/amazon-redshift-utils/blob/master/src/UnloadCopyUtility/util/resources.py#L268) to perform a partial copy to a new cluster. Would a PR to do so be considered?

**Comment by timjell** [comment]
Closing as fix merged into codebase
