### ISSUE TITLE
v_get_obj_priv_by_user throws errors on temp tables

### ISSUE THREAD

**Issue by toddljones** [awslabs/amazon-redshift-utils#473]
I believe we should ignore pg_temp% databases in this view.

Recommend adding the following predicate to the where clause of both queries in the union:
`and schemaname not like 'pg_temp%`

This is needed as the HAS_TABLE_PRIVILEGE() function fails on temporary tables.

**Comment by saeedma8** [comment]
This should be fixed with #638. Please let us know if you still have the issue.
