### ISSUE TITLE
Missing Redshift_DBA_Commands.pptx

### ISSUE THREAD

**Issue by nomadlogic** [awslabs/amazon-redshift-utils#481]
README.md references a presentation:

> # Presentation
> We included a presentation which describes main features of the Amazon-Redshift-Utils including some examples, tips and best practices: Redshift_DBA_Commands.pptx

But this seems to be missing as per my most recent checkout of master, is it no longer available or just an oversight to include it?

```
$ git remote -v
origin	git@github.com:awslabs/amazon-redshift-utils.git (fetch)
$ find . -name 'Redshift_DBA_Commands.pptx' -print
$ echo $?
0
$
```

**Comment by zeubs** [comment]
bump

**Comment by IanMeyers** [comment]
This file was deleted June 12th 2019, presumably because it was out of date relative to the contents of the codebase. I will update the readme, and please message me privately (meyersi@amazon.com) if you would like a copy of this file.
