### ISSUE TITLE
View v_get_blocking_locks is throwing error while creation

### ISSUE THREAD

**Issue by comprakash** [awslabs/amazon-redshift-utils#482]
While to create the view provided in the path - https://github.com/awslabs/amazon-redshift-utils/blob/master/src/AdminViews/v_get_blocking_locks.sql, then I am getting the below error message.

An error occurred when executing the SQL command:
--DROP VIEW admin.v_get_blocking_locks;
/**********************************************************************************************
Purpose: View ...

[Amazon](500310) Invalid operation: cannot change data type of view column "granted";
1 statement failed.

Execution time: 0.05s

**Comment by pvbouwel** [comment]
This sounds like a case where a view already exists but it cannot be replaced in place.  Could you check whether admin.v_get_blocking_locks already exists? And if it does drop it and then try again (currently the drop is commented out in the SQL file). 

For safety you could retrieve the current definition first (https://github.com/awslabs/amazon-redshift-utils/blob/master/src/AdminViews/v_generate_view_ddl.sql) just in case someone has created a view with the same name.

**Comment by saeedma8** [comment]
Could you please let us know if the issue still persists? Please reopen the issue if after dropping you are still seeing this error message. Thank you.
