### ISSUE TITLE
ColumnEncodingUtility: Does the utility take in consideration the existing column encoding?

### ISSUE THREAD

**Issue by patilarpith** [awslabs/amazon-redshift-utils#484]
I noticed that the size of the uncompressed data in the table increased after trying out the column encoding utility on a table.

Table structure before applying the ColumnEncodingUtility changes

|column			|type				|encoding	|distkey	|sortkey	|notnull
|---------------|-------------------|-----------|-----------|-----------|----
|id				|integer			|lzo		|false		|0			|false
|day			|date				|delta32k	|false		|0			|false
|total			|integer			|delta		|false		|0			|false
|percent		|double precision	|none		|false		|0			|false
|score_percent	|double precision	|bytedict	|false		|0			|false

Table structure after applying the ColumnEncodingUtility changes

|column			|type				|encoding	|distkey	|sortkey	|notnull
|---------------|-------------------|-----------|-----------|-----------|----
|id				|integer			|none		|false		|0			|false
|day			|date				|none		|false		|0			|false
|total			|integer			|none		|false		|0			|false
|percent		|double precision	|zstd		|false		|0			|false
|score_percent	|double precision	|zstd		|false		|0			|false

Uncompressed data:

|		  |uncompressed_mb  |total_mb
|-----------|-----------------|-------------
|Old	table |110			  |		880
|New table |330			  |		880

Shouldn't the column encoding utility consider the existing column encoding before making a new recommendation? 

Maybe this example did not result in an increase in the total size of the table but it looks like there is a possibility.

**Comment by IanMeyers** [comment]
Hello - thanks for raising this and sorry to see you are having an issue. Indeed, the encoding utility should not change an encoded column to raw. Can I please ask that you re-run the utility with the following flags, and then post the output here?

`--do-output-False --debug-True`

**Comment by patilarpith** [comment]
@IanMeyers Thank you for the quick response. Did you mean ```--do-execute False```. I don't see a flag by ```--do-output```.

I've run the utility again with ```--debug```. Here is the generated SQL:
https://gist.github.com/patilarpith/0edffe4361cb494005c2eb34b27a8f2c

**Comment by IanMeyers** [comment]
Thanks that helps a lot. It's clear that columns that should be migrated to az64 are instead being converted to raw in error. Let me fix.

**Comment by IanMeyers** [comment]
I think i've tracked down the issue - can you please retest after syncing to 4c52700?

**Comment by patilarpith** [comment]
Looks like the fix works. It recommended the following column encoding

|column			|encoding
|---------------|-----------|
|id				|az64			|
|day			|az64				|
|total			|az64			|
|percent		|zstd	|
|score_percent	|zstd	|

**Comment by IanMeyers** [comment]
👍

**Comment by patilarpith** [comment]
I still see a few columns still encoded as raw:
https://gist.github.com/patilarpith/0a0cbfa716c1e62919f9d38da5cb5528

**Comment by doncorrea-vroom** [comment]
Agreed w/ the above, it still seems like a number of columns are being encoded to raw.

**Comment by saeedma8** [comment]
[Amazon Redshift Column Encoding Utility](https://github.com/awslabs/amazon-redshift-utils/tree/master/src/ColumnEncodingUtility#amazon-redshift-column-encoding-utility) is now deprecated. Instead, please use Redshift's Automatic Table Optimization features through:

```
ALTER TABLE table_name ALTER SORTKEY AUTO;
ALTER TABLE table_name ALTER DISTSTYLE AUTO;
```

https://docs.aws.amazon.com/redshift/latest/dg/t_Creating_tables.html
