### ISSUE TITLE
Error running the script

### ISSUE THREAD

**Issue by dr1pht3r** [awslabs/amazon-redshift-utils#486]
Hi
Total newb here, so sorry for the dumb questions.
I thought that I managed to install all the requirements:
Requirement already satisfied: PyGreSQL in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: aws_utils in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: wheel==0.24.0 in /usr/local/lib/python2.7/dist-packages (from -r /usr/lib/amazon-redshift-utils/src/requirements.txt (line 1))
Requirement already satisfied: pg8000==1.11.0 in /usr/local/lib/python2.7/dist-packages (from -r /usr/lib/amazon-redshift-utils/src/requirements.txt (line 2))
Requirement already satisfied: shortuuid==0.4.3 in /usr/local/lib/python2.7/dist-packages (from -r /usr/lib/amazon-redshift-utils/src/requirements.txt (line 3))
Requirement already satisfied: six==1.10.0 in /usr/local/lib/python2.7/dist-packages (from -r /usr/lib/amazon-redshift-utils/src/requirements.txt (line 4))
Requirement already satisfied: boto3==1.5.3 in /usr/local/lib/python2.7/dist-packages (from -r /usr/lib/amazon-redshift-utils/src/requirements.txt (line 5))
Requirement already satisfied: pgpasslib==1.1.0 in /usr/local/lib/python2.7/dist-packages (from -r /usr/lib/amazon-redshift-utils/src/requirements.txt (line 6))
Requirement already satisfied: boto in /usr/local/lib/python2.7/dist-packages (from aws_utils)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python2.7/dist-packages (from boto3==1.5.3->-r /usr/lib/amazon-redshift-utils/src/requirements.txt (line 5))
Requirement already satisfied: botocore<1.9.0,>=1.8.17 in /usr/local/lib/python2.7/dist-packages (from boto3==1.5.3->-r /usr/lib/amazon-redshift-utils/src/requirements.txt (line 5))
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in /usr/local/lib/python2.7/dist-packages (from boto3==1.5.3->-r /usr/lib/amazon-redshift-utils/src/requirements.txt (line 5))
Requirement already satisfied: docutils>=0.10 in /usr/local/lib/python2.7/dist-packages (from botocore<1.9.0,>=1.8.17->boto3==1.5.3->-r /usr/lib/amazon-redshift-utils/src/requirements.txt (line 5))
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python2.7/dist-packages (from botocore<1.9.0,>=1.8.17->boto3==1.5.3->-r /usr/lib/amazon-redshift-utils/src/requirements.txt (line 5))
Requirement already satisfied: futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from s3transfer<0.2.0,>=0.1.10->boto3==1.5.3->-r /usr/lib/amazon-redshift-utils/src/requirements.txt (line 5))

However, when I try to execute I get this:
Traceback (most recent call last):
  File "./analyze-schema-compression.py", line 61, in <module>
    import aws_utils
  File "/usr/local/lib/python2.7/dist-packages/aws_utils/__init__.py", line 4, in <module>
    from .sqs_consumer import SQSConsumer  # noqa
  File "/usr/local/lib/python2.7/dist-packages/aws_utils/sqs_consumer.py", line 4, in <module>
    from .exceptions import MissingQueueError
ImportError: cannot import name MissingQueueError

What did I do wrong here?

**Comment by IanMeyers** [comment]
Let's please move this to #495
