### ISSUE TITLE
Invalid operation: schema "pg_temp_17" does not exist;

### ISSUE THREAD

**Issue by gorros** [awslabs/amazon-redshift-utils#493]
I get `Invalid operation: schema "pg_temp_17" does not exist;` when I try to select rows from
`v_get_obj_priv_by_user`. Any ideas why this happens?

**Comment by ascott-cs** [comment]
I have the same issue.  Any ideas?

**Comment by toddljones** [comment]
I've had the same issues with this view. I simply excluded pg_temp schems from the subselects

[line #26](https://github.com/awslabs/amazon-redshift-utils/blob/a36138f34052e3a6d9072a4da9e46107da4eacd0/src/AdminViews/v_get_obj_priv_by_user.sql#L26)

[line #29](https://github.com/awslabs/amazon-redshift-utils/blob/a36138f34052e3a6d9072a4da9e46107da4eacd0/src/AdminViews/v_get_obj_priv_by_user.sql#L29)

I simply added `and schemaname not like 'pg_temp%'`

**Comment by saeedma8** [comment]
This should be fixed with issue #638 . Please check it and let us know if the issue still persists. Thank you.
