### ISSUE TITLE
Redshift NodeRole value as uppercase fromAPI 

### ISSUE THREAD

**Issue by RayanaPadmini** [awslabs/amazon-redshift-utils#502]
Hi,
We are retrieving the data of the Redshift and its corresponding Nodes with API
DescribeClustersRequest request = new DescribeClustersRequest();
DescribeClustersResult result = redshiftClient.describeClusters(request);

While retriving the getClusterNodes() from the cluster getting the response as: 
[\{NodeRole: LEADER,PrivateIPAddress: 172.31.36.140,PublicIPAddress: 100.25.54.156}, \{NodeRole: COMPUTE-0,PrivateIPAddress: 172.31.36.126,PublicIPAddress: 54.80.72.156}, \{NodeRole: COMPUTE-1,PrivateIPAddress: 172.31.37.215,PublicIPAddress: 52.0.150.80}]

In the above response the NodeRole values are in the uppercase. But when collecting the metricData [GetMetricStatisticsResult API] we are getting  the dimension values as : 
 [\{Name: ClusterIdentifier,Value: redshift-cluster-1}, \{Name: NodeID,Value: Compute-1}]

We will be forming the dimension values with data collected from the describeClusters, [its getting formed like  [\{Name: ClusterIdentifier,Value: redshift-cluster-1}, \{Name: NodeID,Value: COMPUTE-1}]] in which the case of the NodeId value is different when compared to the metricData dimensions we are getting empty datapoints.
Can you please let me know, if there is any solution for this.

**Comment by IanMeyers** [comment]
Can you please clarify which API you are using when you refer to the `getClusterNodes()` function? This doesn't appear to be a Redshift UDF or Java SDK function, so am unclear where this data is coming from.

**Comment by RayanaPadmini** [comment]
@IanMeyers  Below is the code snippest we are using to collect the data
DescribeClustersRequest request = new DescribeClustersRequest();
		DescribeClustersResult result = redshiftClient.describeClusters(request);
		List<Cluster> clusters = result.getClusters();
		for (Cluster cluster : clusters) {
			System.out.println(cluster.getClusterNodes());
		}

**Comment by IanMeyers** [comment]
Got it. Unfortunately this is an inconsistency between the Java SDK and how Redshift sends metrics to CloudWatch. It's clear that you can apply an uppercase x-form to the data returned from CloudWatch, but I agree this is cumbersome. I would propose that you raise a Trouble Ticket with AWS Support and this will be routed to the Redshift team.

**Comment by timjell** [comment]
Closing this issue as not related to this repository code
