### ISSUE TITLE
ColumnEncodingUtility is breaking materialized views 

### ISSUE THREAD

**Issue by kevinviraudDH** [awslabs/amazon-redshift-utils#503]
Hello,

The ColumnEncodingUtility currently does not make the distinction between a regular table and a materialized view and it ends up breaking the materialized views when being run.

As far as I can see, when creating and refreshing a materialized view,  Redshift seem to do more or less the following (assume the view name is my_materialized_view) : 
- Create a table **mv_tbl__my_materialized_view_0** (owner rdsdb)
- Create a view **vmy_materialized_view** (owner current user) that point to **mv_tbl__my_materialized_view_0**

The ColumnEncodingUtility is picking up **mv_tbl__my_materialized_view_0** since it is a regular table and if compresion is needed : 
- Create a new migrated **mv_tbl__my_materialized_view_0_$mig**
- DROP **CASCADE** on **mv_tbl__my_materialized_view_0** which in returns drops *my_materialized_view*
- Rename **mv_tbl__my_materialized_view_0_$mig** to **mv_tbl__my_materialized_view_0**

**Suggestion for a quick fix**
Ignore tables where owner is **rdsdb** and assume Redshift optimized it already. 
See : https://github.com/awslabs/amazon-redshift-utils/blob/master/src/ColumnEncodingUtility/analyze-schema-compression.py#L1023

**Long term fix** 
Better handling of both non binding and materialized views and avoid CASCADE DROP.

Thanks you.

cc @IanMeyers

**Comment by joeharris76** [comment]
Thanks for raising this issue. We will resolve it in the update of the utility.

**Comment by saeedma8** [comment]
[Amazon Redshift Column Encoding Utility](https://github.com/awslabs/amazon-redshift-utils/tree/master/src/ColumnEncodingUtility#amazon-redshift-column-encoding-utility) is now deprecated. Instead, please use Redshift's Automatic Table Optimization features through:

```
ALTER TABLE table_name ALTER SORTKEY AUTO;
ALTER TABLE table_name ALTER DISTSTYLE AUTO;
```

https://docs.aws.amazon.com/redshift/latest/dg/t_Creating_tables.html
