### ISSUE TITLE
v_generate_tbl_ddl.sql does not seem to export database COMMENTs

### ISSUE THREAD

**Issue by epankala** [awslabs/amazon-redshift-utils#511]
After running v_generate_tbl_ddl.sql I was unable to find any of the table or column 'COMMENT's been exported.

ref: https://docs.aws.amazon.com/redshift/latest/dg/r_COMMENT.html

SELECT a.attname,
  pg_catalog.format_type(a.atttypid, a.atttypmod),
  pg_catalog.col_description(a.attrelid, a.attnum)
FROM pg_catalog.pg_attribute a
WHERE a.attrelid = 'table rel id here' AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY col_description;

**Comment by timjell** [comment]
Closing issue as resolved by #521
