### ISSUE TITLE
boto3 execute_statementfor redshift

### ISSUE THREAD

**Issue by hardwaals** [awslabs/amazon-redshift-utils#514]
Kindly assist. After running below code as written in the boto3 documentation. I got the "AttributeError: 'Redshift' object has no attribute 'execute_statement'" error. What am I doing wrong?

import boto3
client = boto3.client('redshift-data')
response = client.execute_statement(
    ClusterIdentifier='myCluster',
    Database='dev',
    DbUser='awsuser',
    Sql='create table scorecard (name varchar20(),dept varchar30())',
    StatementName='My Table',
    WithEvent=False
)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/client.py in __getattr__(self, item)
    573         raise AttributeError(
    574             "'%s' object has no attribute '%s'" % (
--> 575                 self.__class__.__name__, item)
    576         )
    577 

AttributeError: 'Redshift' object has no attribute 'execute_statement'

**Comment by IanMeyers** [comment]
You may need to update your version of boto3 to have access to the new data-api methods.

**Comment by hardwaals** [comment]
Thanks @IanMeyers .I was able to upgrade and got it working.
