### ISSUE TITLE
Analyze Vacuum Utility: No Connection was established

### ISSUE THREAD

**Issue by msrinathr** [awslabs/amazon-redshift-utils#520]
I am running Analyze Vacuum Utility as below from src folder
python AnalyzeVacuumUtility/analyze-vacuum-schema.py --db <dbname> --db-user <user> --db-port 5439 --db-pwd <pswd>  --db-host <hostname> --output-file output.log --analyze-flag=True

Getting below error:

Traceback (most recent call last):
  File "AnalyzeVacuumUtility/analyze-vacuum-schema.py", line 140, in <module>
    main(sys.argv)
  File "AnalyzeVacuumUtility/analyze-vacuum-schema.py", line 131, in main
    result = analyze_vacuum.run_analyze_vacuum(**args)
  File "AnalyzeVacuumUtility/lib/analyze_vacuum.py", line 696, in run_analyze_vacuum
    raise Exception("No Connection was established")
Exception: No Connection was established

**Comment by alessiosavi** [comment]
I have the same issue, seems that the error is related to the `ssl`

```text
-- 2021-02-03 16:48:41.625186 [14808] Connected to CloudWatch in us-east-1
-- 2021-02-03 16:48:41.625186 [14808] Using Cluster Name super-secret-client-cluster
-- 2021-02-03 16:48:41.626153 [14808] Supplied Args:
{'db': 'dev', 'db_user': 'dont-watch-my-user!', 'db_pwd': 'dont-watch-my-pass!', 'db_host': 'super-secret-client-cluster.c4ce0antopqh.us-east-2.redshift.amazonaws.com', 'db_port': 5439, 'analyze_flag': True, 'vacuum_flag': True, 'debug': 'True', 'ignore_errors': 'False', 'require_ssl': False, 'schema_name': 'public'}
-- 2021-02-03 16:48:41.627183 [14808] Connect super-secret-client-cluster.c4ce0antopqh.us-east-2.redshift.amazonaws.com:5439:dev:awsuser
Exception on Connect to Cluster: connect() got an unexpected keyword argument 'ssl'
Unable to connect to Cluster Endpoint
Traceback (most recent call last):
  File "analyze-vacuum-schema.py", line 140, in <module>
    main(sys.argv)
  File "analyze-vacuum-schema.py", line 131, in main
    result = analyze_vacuum.run_analyze_vacuum(**args)
  File "lib\analyze_vacuum.py", line 696, in run_analyze_vacuum
    raise Exception("No Connection was established")
Exception: No Connection was established
```

**Comment by aseem-poloniex** [comment]
> pip3 install pg8000==1.11.0

This version fixed everything

**Comment by hpiwowar** [comment]
I had the same problem and it fixed it for me too.  Thanks!

**Comment by timjell** [comment]
Closing this issue. The utility has migrated to use the redshift_connector instead of pg8000 and the require-ssl flag is redundant.
