### ISSUE TITLE
Credentials in the .env file

### ISSUE THREAD

**Issue by nazrulkamaruddin-tomtom** [awslabs/amazon-redshift-utils#530]
My colleague noticed that the .env file checked in to this repo has credentials info.

Is that deliberate?

https://github.com/awslabs/amazon-redshift-utils/blob/master/.env

**Comment by IanMeyers** [comment]
hello - thanks for the heads up. This is for a DB that has long been torn down but have put `.env` in `.gitignore` to prevent anyone else having issues.
