### ISSUE TITLE
AnalyzeVacuumUtility - Unused arg in analyze-vacuum-schema.py 

### ISSUE THREAD

**Issue by MatchaBlast** [awslabs/amazon-redshift-utils#539]
Hi,

I noticed that the `main(argv)` function in analyze-vacuum-schema.py accepting argv as an argument (line 116) but it doesn't use it anywhere the `main(argv)` function. I'm confused on what the purpose of passing this argv. Please advise. 

Thank you,

**Comment by timjell** [comment]
The command line arguments are parsed earlier in the script. You are right, the argv variable is not used in the main function. 

The command arguments can be used from either the sys.argv or from the earlier global variable 'parse_args'. This doesnt affect in any way the script, so leaving it as is.
