### ISSUE TITLE
ColumnEncodingUtility needs to surround table and column names in double quotes

### ISSUE THREAD

**Issue by cswilliams** [awslabs/amazon-redshift-utils#54]
Ran into two bugs when I ran the column encoding utility on our database:

1) It gives syntax errors when it encounters a table with a space in it, for example "Table 200". 

2) It gives syntax errors if it encounters a column name that is a reserved keyword, e.g. "open".  

I believe the fix to both of these issues is that it needs to surround table and column names in double quotes in all of the queries that it generates.

**Comment by IanMeyers** [comment]
Hi Chris,

Thanks for pointing these items out. TBH, I've not planned for supporting either of those corner cases, but we can look to add this support. I will have a look at addressing this, but just to be clear, was the issue that the output script couldn't be generated, or that the generated script couldn't be run?

Thx,

Ian
