### ISSUE TITLE
v_generate_tbl_ddl : Invalid operation: value too long for type character varying(798)

### ISSUE THREAD

**Issue by shaounak** [awslabs/amazon-redshift-utils#548]
This may be occurring due to the comments on the object or some part of table DDL.

**Comment by timjell** [comment]
Thanks for the report. Do you have any other details you can provide to help us track down the issue? If you can provide some more details about the table/comment that is causing the issue that will help us fix this issue.

**Comment by timjell** [comment]
Closing the ticket as not reproduceable given the limited information provided. If more details can be given so we can track down the issue then we can reopen this ticket.

**Comment by vare7** [comment]
I am getting similar error. Error screenshot: https://i.imgur.com/CglvPh1.png

**SQL Statement:** 
select ddl
from admin.v_generate_tbl_ddl
where schemaname = 'schema_name_goes_here';
