### ISSUE TITLE
v_extended_table_info.sql : none encoding incorrect reporting due to multiple attencodingtype linked with it.

### ISSUE THREAD

**Issue by devopam** [awslabs/amazon-redshift-utils#557]
I checked pg_attribute for attencodingtype ( translating to None ) using format_encoding() and found that 128 also equates to None , other than 0.

So, 
line 112 : 
SUM(CASE WHEN a.attencodingtype = 0 THEN 0 ELSE 1 END) AS encoded_cols,

might need to be changed with :
SUM(CASE WHEN a.attencodingtype IN  (0,128) THEN 0 ELSE 1 END) AS encoded_cols,

**Comment by timjell** [comment]
Thanks for the fix, this has been updated.
