### ISSUE TITLE
ImportError when running redshift-upload-copy.py utility

### ISSUE THREAD

**Issue by 580farm** [awslabs/amazon-redshift-utils#56]
Hello,

I'm getting this trace when I attempt to run the utility:

[root@host UnloadCopyUtility]# python redshift-unload-copy.py config.json us-west-2
Traceback (most recent call last):
  File "redshift-unload-copy.py", line 24, in <module>
    import pg
  File "/usr/lib64/python2.6/site-packages/pg.py", line 31, in <module>
    from _pg import *
ImportError: /usr/lib64/python2.6/site-packages/_pg.so: undefined symbol: PQescapeIdentifier

Not sure what this entails, I verified my configuration's JSON looks correct. Anyone who's familar with this might be able to tell me what I'm missing?

**Comment by 580farm** [comment]
Looks as tho it was a library issue since I was using postgreSQL8.x libraries. I've updated them but I'm getting a different error now:


Traceback (most recent call last):
  File "redshift-unload-copy.py", line 28, in <module>
    from boto import kms, s3
ImportError: cannot import name kms

**Comment by IanMeyers** [comment]
Looks like boto needs an update. Can you please run ```pip install --upgrade boto``` and see if that resolves the issue?

Ian

**Comment by jws1987** [comment]
Hi,

I'm getting the exact same error when running the analyze compression utility.  I've run 'pip install --upgrade boto' but still get the same issue.

Jon

**Comment by marios-zindilis** [comment]
This utility requires `pg` which in turn requires libraries installed as part of the Postgres client, version 9.0 or higher. Namely `PQescapeIdentifier` appeared in 9.0. Judging from your library path `/usr/lib64/python2.6/site-packages/pg.py` I see that your version of Python is 2.6, so I'm going to hazard a guess that you are running CentOS 6.x, which includes Postgres 8.x in the updates repo, or another distribution that displays similar behaviour.

Can either @580farm or @jws1987 check your version of Postgres client and update this issue?
