### ISSUE TITLE
To copy views with DDl from source to destination

### ISSUE THREAD

**Issue by caeser1996** [awslabs/amazon-redshift-utils#575]
Hey Guys,
Is there anything from which we can copy views from source to destination?
I got the view DDL but the issue is they are dependent on other views.

**Comment by timjell** [comment]
Hi, I would suggest you use the AdminViews to generate all the DDLS of the existing objects. You can then create them all in the destination. Ones to check are the Schema DDL (https://github.com/awslabs/amazon-redshift-utils/blob/master/src/AdminViews/v_generate_schema_ddl.sql), Table DDL (https://github.com/awslabs/amazon-redshift-utils/blob/master/src/AdminViews/v_generate_tbl_ddl.sql) and View DDL (https://github.com/awslabs/amazon-redshift-utils/blob/master/src/AdminViews/v_generate_view_ddl.sql).
