### ISSUE TITLE
Analyze/Vaccum default arguments

### ISSUE THREAD

**Issue by Venkat9119** [awslabs/amazon-redshift-utils#578]
Hello, I see in analyze-vacuum-schema.py, script defined defaults as TRUE for analyze and Vacuum. However, In document, it says FALSE as default value. If I update the command during runtime, it is still taking effect of the defaults configured in 'analyze-vacuum-schema.py' . Do I have to modify the defaults in the analyze-vacuum-schema.py file?
Also setting it to TRUE means to do actual Vacuum/analyze? 

example by running below command, doesn't take any affect and output still shows matching the .py file
--debug True  --ignore-errors=False  --ignore-errors False  --require-ssl=True --schema-name public  --analyze-flag False
OR
--debug True  --ignore-errors=False  --ignore-errors False  --require-ssl=True --schema-name public  
OR
--debug True  --ignore-errors=False  --ignore-errors False  --require-ssl=True --schema-name public  --vacuum-flag False

--https://github.com/awslabs/amazon-redshift-utils/blob/master/src/AnalyzeVacuumUtility/analyze-vacuum-schema.py

arser.add_argument("--analyze-flag", dest="analyze_flag", default=True, type=bool,
                    help="Flag to turn ON/OFF ANALYZE functionality (True or False : Default = True ")

parser.add_argument("--vacuum-flag", dest="vacuum_flag", default=True, type=bool,
                    help="Flag to turn ON/OFF VACUUM functionality (True or False :  Default = True")

Command I use during runtime:
python analyze-vacuum-schema.py  --db=xx--db-user=xxx--db-pwd=xxxxx --db-port=xxx--db-host=xxxxx  --output-file C:\Users\test.log --debug True  --ignore-errors=False  --ignore-errors False  --require-ssl=True --schema-name public  --vacuum-flag False

or

python analyze-vacuum-schema.py  --db=xx--db-user=xxx--db-pwd=xxxxx --db-port=xxx--db-host=xxxxx  --output-file C:\Users\test.log --debug True  --ignore-errors=False  --ignore-errors False  --require-ssl=True --schema-name public  ----analyze-flag False

**Comment by timjell** [comment]
Behaviour for the 'analyze-flag' and the 'vacuum-flag' have been updated. The values are now required to be passed in on the command line, and the default values have been changed to 'False'. Readme file has been updated to reflect this.

Note that the 'require-ssl' flag has been removed, this is set as True for all connections for best security.
