### ISSUE TITLE
QMR results not getting alerted via email

### ISSUE THREAD

**Issue by da-prateeka** [awslabs/amazon-redshift-utils#586]
We have deployed this utility in our environment correctly. stl_wlm_rule_action.actions table is also getting updated but we are not getting notified via mail.

Can anybody help where might be the disconnect??

![image](https://user-images.githubusercontent.com/80520930/139662893-6a36e561-78b1-4e1b-846c-176fd7695589.png)

Screenshot attached for the lambda function

**Comment by saeedma8** [comment]
Hi @da-prateeka, I am not sure if you have already confirmed subscription to [SNS](https://docs.aws.amazon.com/sns/latest/dg/sns-email-notifications.html) ? "You must confirm the subscription before the email address can start to receive messages."

Also, there was an issue in [README](https://github.com/awslabs/amazon-redshift-utils/tree/master/src/QMRNotificationUtility#6-add-an-encrypted-password) regarding generating encrypting password for CIPHERTEXT parameter. The issue has been already fixed.

Could you please follow all steps again and reopen the issue if the problem persists? Please send Lambda log output.
