### ISSUE TITLE
v_generate_tbl_ddl produces syntactically DDL when pg_constraint is larger than 100000000  

### ISSUE THREAD

**Issue by beipang** [awslabs/amazon-redshift-utils#595]
Hello team!

We ran into the edge case when the `pg_constraint.id` is larger than 100000000.
In this case, the `seq`  calculated by 
``` sql

    , 200000000 + CAST(con.oid AS INT)      AS seq
        ...
    FROM pg_constraint AS con
```
will exceeds 300000000.

The resulting DDL will have the constraint in the wrong section, which looks like:

```
   seq            |        ddl               |
------------+----------------+
100000001 | id INTEGER   ENCODE az64
100000002 | ,column2 VARCHAR(16383)   ENCODE lzo
299999999| )
300000001 | DISTSTYLE KEY
308544136 | 	,UNIQUE (id)
400000002 | DISTKEY (user_id)
499999999 | SORTKEY (
```

One possible fix is to add a modulo of 100000000 on the `con.oid` during the seq calculation

**Comment by timjell** [comment]
Fix has been implemented
