### ISSUE TITLE
System Object Persistence Utility fails when attempting to create `history.hist_stl_load_errors`

### ISSUE THREAD

**Issue by patbl** [awslabs/amazon-redshift-utils#601]
`CREATE TABLE IF NOT EXISTS history.hist_stl_load_errors (LIKE STL_LOAD_ERRORS);` appears here:

https://github.com/awslabs/amazon-redshift-utils/blob/5c339b391b659e57c792eae5ab4435195751a6d4/src/SystemTablePersistence/lib/history_table_creation.sql#L3

That command, plus at least of one of the following ones (`CREATE TABLE IF NOT EXISTS history.hist_stl_wlm_query (LIKE stl_wlm_query);` fails because the argument to `LIKE` is a view rather than a table:

```
CREATE TABLE IF NOT EXISTS history.hist_stl_load_errors (LIKE STL_LOAD_ERRORS);
ERROR:  inherited relation "stl_load_errors" is not a table
```

A more-general question: I've run into a bunch of minor bugs and compatibility issues in the SystemPersistenceUtility CloudFormation stack that I've had to work around. These include

1. `S3ConfigPath`'s `AllowedPattern` doesn't allow periods in bucket names (see https://github.com/awslabs/amazon-redshift-utils/issues/347#issuecomment-431107695):

https://github.com/awslabs/amazon-redshift-utils/blob/5c339b391b659e57c792eae5ab4435195751a6d4/src/SystemTablePersistence/deploy-systable-standalone.yaml#L35

2. `KmsKeyARN`'s `AllowedPattern` has a forward slash rather than a colon before the 12-digit portion:

https://github.com/awslabs/amazon-redshift-utils/blob/5c339b391b659e57c792eae5ab4435195751a6d4/src/SystemTablePersistence/deploy-systable-standalone.yaml#L40

3. The Python runtime is `python2.7`, which AWS Lambda no longer supports:

https://github.com/awslabs/amazon-redshift-utils/blob/5c339b391b659e57c792eae5ab4435195751a6d4/src/SystemTablePersistence/deploy-systable-standalone.yaml#L59

4. It uses an old version of LambdaRedshiftRunner (1.4 instead of 1.5.1):

https://github.com/awslabs/amazon-redshift-utils/blob/5c339b391b659e57c792eae5ab4435195751a6d4/src/SystemTablePersistence/deploy-systable-standalone.yaml#L62

Is SystemPersistenceUtility being maintained? It looks as though substantive development [ceased in late 2018](https://github.com/awslabs/amazon-redshift-utils/commits/master/src/SystemTablePersistence). I'm wondering whether I should create separate issues for the problems I listed.

**Comment by timjell** [comment]
Hi, thanks for the summary. I have been looking into this and updating for Python3 as well as the view issues. Hope to have an update for this fairly soon.

**Comment by timjell** [comment]
Hi @patbl, can you try downloading the current versions and checking again? We have deployed fixes for the issue so that the SQL creates a table from the view, then uses that temporary table in the creation of the object. We have also updated the LambdaRedshiftRunner package, and lots of bug fixes! I will close this ticket, if you experience any of the same issues please let me know and we can reopen.
