### ISSUE TITLE
Update Simple replay utility readme to explain usage of node config utility instead of cloudformation template for automation

### ISSUE THREAD

**Issue by kaulvishal** [awslabs/amazon-redshift-utils#610]
Hi,

Since the cloud formation template has been decommissioned and deleted in recent commit. Could you please update the readme to detail the steps that should be taken to automate the node migration activity using node config utility.Also, Please let me know if it is okay to perform the evaluation using previous version which had cloud formation template?

**Comment by Brandon-Schur** [comment]
The README has been updated to point to the node configuration utility and blog which has instructions on the setup.  We have further near term plans to simplify this process.

https://github.com/awslabs/amazon-redshift-utils/commit/0d11fcdb7ec72345f9333b8dbc174e8e2834f2f3
