### ISSUE TITLE
Redshift Connection Failed: exception name 'password' is not defined

### ISSUE THREAD

**Issue by gyuan-cars** [awslabs/amazon-redshift-utils#618]
Getting below issue for amazon-redshift-utils:

START RequestId: 5e7221ca-06a1-46e5-8ae6-16dfb87c928e Version: $LATEST
Redshift Connection Failed: exception name 'password' is not defined
END RequestId: 5e7221ca-06a1-46e5-8ae6-16dfb87c928e
REPORT RequestId: 5e7221ca-06a1-46e5-8ae6-16dfb87c928e	Duration: 1.23 ms	Billed Duration: 2 ms	Memory Size: 128 MB	Max Memory Used: 31 MB	

Can anyone help?

Thanks,

Gordon

**Comment by IanMeyers** [comment]
Can you please clarify which utility you are running?

**Comment by gyuan-cars** [comment]
Amazon Redshift Utilities

**Comment by gyuan-cars** [comment]
QMRNotificationUtility

**Comment by IanMeyers** [comment]
This appears to be due to an incompatibility with the latest versions of pg8000, that has changed the structure of the `connect()` method. Will attempt to assign to someone who can address this.

**Comment by gyuan-cars** [comment]
The new syntax is: conn = pg8000.connect(database=database, user=user, password=password, host=host, port=port, ssl_context=ssl). However, the Ciphertext password doesn't work properly. I have to hard code password in Lambda function. Any idea?

**Comment by timjell** [comment]
Connection details updated to use redshift_connector and not pg8000.

**Comment by harish422** [comment]
@gyuan-cars  Hi Gordon, Did this fix resolve the issue ? I am using the latest master branch with this fix. I am seeing the same issue.

**Comment by harish422** [comment]
Opened another ticket for this one @timjell @IanMeyers 

https://github.com/awslabs/amazon-redshift-utils/issues/623
