### ISSUE TITLE
Keep getting "Redshift Connection Failed: exception name 'password' is not defined" after following amazon-redshift-utils steps exactly.

### ISSUE THREAD

**Issue by harish422** [awslabs/amazon-redshift-utils#623]
Hi, I have followed steps from amazon-redshift-utils github page to implement the notification utility based on QMR rule. But some how i keep getting below error in lambda logs. looks like lambda is unable to authenticate to redshift cluster though the password provided is correct. Is there any workaround for this one ? 

https://github.com/awslabs/amazon-redshift-utils/tree/master/src/QMRNotificationUtility

I noticed a similar issue reported before as below. seems like the connect function is replaced with redshift_connect. I see this change in my lambda code. But still the same issue.

This is the issue that got fixed :
https://github.com/awslabs/amazon-redshift-utils/issues/618

Please let me know what else can i do here. this is currently blocking me.

START RequestId: 8418bd00-21d2-4d07-8a11-fb94e6d8deb7 Version: $LATEST
--
Redshift Connection Failed: exception name 'password' is not defined
END RequestId: 8418bd00-21d2-4d07-8a11-fb94e6d8deb7
REPORT RequestId: 8418bd00-21d2-4d07-8a11-fb94e6d8deb7	Duration: 1.50 ms	Billed Duration: 2 ms	Memory Size: 128 MB	Max Memory Used: 70 MB

@IanMeyers  @timjell

**Comment by saeedma8** [comment]
Hi Harish, I am not sure if you face this issue during the setup when generating CIPHERTEXT. It must be the [fileb://](https://docs.aws.amazon.com/cli/latest/reference/kms/encrypt.html#examples) prefix to specify the --plaintext parameter. README will be updated shortly to cover this. 

### Not working:
`
$ aws --region us-east-1 kms encrypt --key-id $KMSKEYID --plaintext file://passwd.txt --query 'CiphertextBlob' --output text

Invalid base64: "MyPassword"
`
### Working:
`
$ aws --region us-east-1 kms encrypt --key-id $KMSKEYID --plaintext fileb://passwd.txt --query 'CiphertextBlob' --output text
`

**Comment by saeedma8** [comment]
Hi Harish, README updated. Could you please follow all steps again and reopen the issue if the problem persists? Thank you.

**Comment by harish422** [comment]
@saeedma8  Thank you. seems like that fixed the issue. Now it works :)

One last question I have is, in step 9 it asks to "click" the link in the email to subscribe to receiving the notification emails right? Is clicking the lonk mandatory ? 

The reason I am asking this is because I would like to provide our pagerduty email address so that our pagerduty will trigger on-call alerts whenever an email is sent to pagerduty's email address. But in this case there is no way to "click" the link in pagerduty's email to subscribe. If clicking the link is not required, we are good may be. Otherwise any workaround to make this use case work ?

Right now trigerring an email to my email or any team member email has no significant value. we have to manually track the notification alerts in email.

**Comment by saeedma8** [comment]
Hi Harish, thank you and glad to hear that works. I replied to your concern in the issue #628
