### ISSUE TITLE
Scripts and Views that scan all schemas now need to exclude pg_automv

### ISSUE THREAD

**Issue by Shearer-ghub** [awslabs/amazon-redshift-utils#634]
Admins views and scripts that scan all schemas need to be revised to exclude pg_automv. For example: 
v_get_obj_priv_by_user.sql
The schema only excludes pg_internal, it also needs to exclude pg_automv as part of the feature Auto Materialized views that was recently released. 

WHERE schemaname not in ('pg_internal','pg_automv')

**Comment by saeedma8** [comment]
Hi @Shearer-ghub, hope you are doing well and thank you for raising the issue. We have already fixed those affected area and merged the code. Please let us know if there is any other issue. Thank you.
