### ISSUE TITLE
permission denied for relation stv_tbl_perm

### ISSUE THREAD

**Issue by kicks66** [awslabs/amazon-redshift-utils#648]
When running the column encoding utility, I receive the following error:

```
 raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': '42501', 'M': 'permission denied for relation stv_tbl_perm', 'F': '../src/pg/src/backend/catalog/aclchk.c', 'L': '2763', 'R': 'aclcheck_error'}
```

I have tried allowing privelages with `GRANT ALL PRIVILEGES ON stv_tbl_perm to awsuser;` but this has not resolved. I also tried to run `SELECT * FROM stv_tbl_perm` and this failed with `ERROR:  permission denied for relation stv_tbl_perm`

Command I am running:

`python3 analyze-schema-compression.py --db xxx --db-user yyyy --db-pwd zzz --db-host redshift.xxxxxx.eu-west-1.redshift-serverless.amazonaws.com`

**Comment by timjell** [comment]
Hi, thanks for raising the issue. This is a permissions problem, as the user you are running with is a normal user. The permissions on that view are:

> STV_TBL_PERM is visible only to superusers

from the docs at https://docs.aws.amazon.com/redshift/latest/dg/r_STV_TBL_PERM.html.

You can use an existing superuser, or create a new one by including the CREATEUSER word as part of the user creation. Check the docs at https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_USER.html

**Comment by timjell** [comment]
I should also add that this utility is being phased out, as the functionality exists within Redshift. Check out the auto encoding feature at https://docs.aws.amazon.com/redshift/latest/dg/c_Compression_encodings.html

**Comment by zachliu** [comment]
no, this is a redshift serverless problem. even "superuser" is unable to query this table on serverless

**Comment by Amanrajput000** [comment]
I am a superuser and redshift is not serverless but still unable to access stv_tbl_perm and getting the same error- permission denied for relation stv_tbl_perm. Can anyone please help me ?
