### ISSUE TITLE
[UnloadCopyUtility] Can't migrate between regions 

### ISSUE THREAD

**Issue by filoleg** [awslabs/amazon-redshift-utils#70]
After exporting the DB successfully into a staging S3 location with the same region as the source, I get error when trying to import it into the target redshift from the staging S3  "The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint," which is indicating of me trying to access the bucket of wrong region. The source redshift and S3 are in us-east-1, and the target is in eu-west-1. The exact command I ran was "python redshift-unload-copy.py ./config.json us-east-1". Just for the sake of it I tried eu-west-1, but it failed at an even earlier stage of trying to export the DB from source to the staging S3.

Can anyone else confirm inability to migrate from one region to another? If it is a confirmed issue, I will submit a pull request.

Thank you.

**Comment by kerbelp** [comment]
If you use COPY command to load data to Redshift, you can add the option 'region us-east-1' to the COPY  command and your Redshift cluster will know to take the data from S3 'us-east-1' region and not the region of the Redshift cluster.
For example:
COPY table_name 
FROM data_source
CREDENTIALS 'aws_access_credentials'
REGION 'us-east-1';

Does it answer your question?

**Comment by filoleg** [comment]
If I use direct COPY command, you are correct, it should work, but within the python script provided it just simply didn't work, which is the whole point.

**Comment by IanMeyers** [comment]
Added support for cross region copy in 5432cd0
