### ISSUE TITLE
admin.v_space_used_per_tbl Issue

### ISSUE THREAD

**Issue by williammarino** [awslabs/amazon-redshift-utils#71]
The recommended column on the above view doesn't seem to work.  When you look at
 `select * from SVV_TABLE_INFO ` tables that are unsorted are still showing up as VACUUM recommended in the below.  I haven't given it much thought yet but will review the code tonight

```
CASE WHEN a.rows = 0 THEN 'n/a'
			WHEN (a.unsorted_rows::FLOAT / a.rows::FLOAT) * 100 >= 20 THEN 'VACUUM recommended'
			ELSE 'n/a'
		END AS recommendation
```

I reviewed the code and it looks good.  Here is the scenario I run the view provided and pick a table that has VACUUM RECOMMENDED  then run

`vacuum zeus.audit_data_validation;
analyze zeus.audit_data_validation;` 

Run the view again expecting the message to go away but it is still there.  Is there a delay of any nature?

**Comment by williammarino** [comment]
I think in my own research I found out the reason but please confirm.  Does the unsorted_rows column rely on a sort_key?  For tables that have no sort key the unsorted_rows will always be 100%.

**Comment by chriz-bigdata** [comment]
Any table without a sortkey stores data in the unsorted segment of the table. So 100% of rows are unsorted in these cases.
