### ISSUE TITLE
Error on View Permissions Query

### ISSUE THREAD

**Issue by jthigpen** [awslabs/amazon-redshift-utils#80]
When I try to `select * from admin.v_get_view_priv_by_user` I get an error:

```
ERROR:  cross-database references are not implemented: "facebookappmktg.facebook_adgroup_1234567__conversion_specs__action.type"
Query failed
PostgreSQL said: cross-database references are not implemented: "facebookappmktg.facebook_adgroup_1234567__conversion_specs__action.type"
```

I'm not sure what to make of that or how to begin debugging it.

**Comment by shaunymca** [comment]
Added a pull request for this. https://github.com/awslabs/amazon-redshift-utils/pull/81

**Comment by jthigpen** [comment]
@shaunymca This issue also affects at least these other views in this project.
```
v_get_obj_priv_by_user
v_generate_user_object_permissions
v_get_view_priv_by_user
v_dba_tab_privs
```

**Comment by shaunymca** [comment]
Cool, I'll take a look and see what I can do there.

**Comment by chriz-bigdata** [comment]
`v_dba_tab_privs` is not part of this project, but I applied a fix using `QUOTE_IDENT()` to the other 3 views you mentioned.
