### ISSUE TITLE
Vacuum "delete only" on table with interleaved key

### ISSUE THREAD

**Issue by SublimeJohann** [awslabs/amazon-redshift-utils#92]
Hello,
we have an issue with the script AnalyzeVacuumUtility/analyze-vacuum-schema.py

both phase
Extracting Candidate Tables for vacuum based on the alerts... (line 262 as 05/20)
and
Extracting Candidate Tables for vacuum ... (line 320 as 05/20)

require tables to not having interleaving sortkey for being valid for vacuum delete only

We have some huge tables with interleaved sort key, and we regulary delete rows on them, and the vacuum delete only is never launched by the script, so the tables got bigger every day.

Also the vacuum reindex is not launched either because the max intearleave skew is not very big

Do you think it would be good option to not check the table sort key when using parameter "delete only" on vacuum ?

Thank you

**Comment by IanMeyers** [comment]
Understood. These are both valid points, and I think the right extension would be to specifically handle the cases of understanding when a 'vacuum reindex' is needed for tables. If you are in a position to contribute a pull request for this it would be gratefully received. Otherwise I will raise this to the original author and see if they can spend some time on it.

**Comment by SublimeJohann** [comment]
I would need help for me to do it. Like how to get tables with high percentage of rows with "to delete flag". I am pretty new to redshift, i am not aware yet of all system tables. Wiser choice would be to ask the author, but i can try to spend some time to do it.

**Comment by timjell** [comment]
Closing this issue as Redshift now has automatic background sorting and vacuuming (https://docs.aws.amazon.com/redshift/latest/dg/t_Reclaiming_storage_space202.html) . This utility is being moved to maintenance mode, and we are not planning on adding any new features to the code.
