### ISSUE TITLE
Issues with v_generate_tbl_ddl.sql

### ISSUE THREAD

**Issue by jrandrews** [awslabs/amazon-redshift-utils#93]
Hello --
Thanks so much for these great scripts.
I've been using them for various Redshift diagnostics. I think I have found an issue with v_generate_tbl_ddl. When I try to run it I get this error message:

```
SELECT
 schemaname
 ,tablename
 ,seq
 ,ddl
FROM
 (
 SELECT
  schemaname
  ,tablename
  ,seq
  ,ddl
 FROM
  (
  --DROP TABLE
  SELECT
   n.nspname AS s...

[Amazon](500310) Invalid operation: syntax error at or near "SELECT";
```
I've been trying to troubleshoot this and figure out the query issue but it is a rather large query.
A couple questions to start:

1. Is there a reason to have the ORDER BY clauses in the subqueries? I don't think these actually do anything. I'm actually a bit surprised Redshift allows this; SQL Server doesn't. 

    Examples: 
    Line 81,    ORDER BY a.attnum
    Line 93,   ORDER BY seq
    Line 141,   ORDER BY abs(a.attsortkeyord))
    Line 152,   ORDER BY abs(a.attsortkeyord)
    Line 181,     ORDER BY seq

    More info on why ORDER BY in subqueries isn't useful and could actually be harmful by having the database do extra unnecessary work :http://stackoverflow.com/questions/5119190/oracle-sql-order-by-in-subquery-problems. 
    
    I realize the stackoverflow discussion above is about Oracle, but I think the general point is relevant for any RDBMS.

    I have found that sub-parts of the query will work if I remove the excess ORDER BY clauses.

2. I think there are some extra parentheses?
    Examples:
    Line 127,   UNION (SELECT
    Line 141,   ORDER BY abs(a.attsortkeyord)) -- This time at the end, aside from the ORDER BY
    Line 157,   WHERE c.relkind = 'r' )

3. Does the query as a whole run correctly for you? I have been using SQL Workbench/J and just want to make sure it isn't some sort of query formatting or codepage issue.

Thanks!

**Comment by chriz-bigdata** [comment]
The first issue is caused by an issue with how SQL comments are handled within querytext by the Redshift JDBC 1.1.13 driver. You can mitigate this behavior with the 1.1.10 version of the Redshift driver until we release the next version.

The ORDER BY clauses are to ensure a consistent positioning of columns, but testing against the pg_catalog tables shows this consistent ordering is enforced already. These are likely to be redundant - will test and remove if confirmed to be the case.

**Comment by jrandrews** [comment]
Thank you, reverting from the Redshift JDBC 1.1.13 driver to the 1.1.10 driver worked.

I'm curious -- I can't see any references now to the 1.1.13 driver anywhere but I know I must have downloaded it from somewhere before. Was the 1.1.13 driver formerly available on Amazon's site and then removed due to some issues found with the driver?

**Comment by chriz-bigdata** [comment]
We had previously identified the issue you raised here and removed the driver while we work on a fix.

**Comment by chriz-bigdata** [comment]
> Is there a reason to have the ORDER BY clauses in the subqueries? ... I think there are some extra parentheses?

We globally sort by `seq` which is properly generated by incrementing `attnum` or `abs(a.attsortkeyord)` to maintain column order, so there is no meaningful value in these redundant ORDER BY clauses in the various subqueries. Benchmarks against a version of the VIEW where these are omitted resulted in a non-measurable performance change. I will remove these as well as the redundant parenthesis.

**Comment by jrandrews** [comment]
Thanks, chrisz. I really appreciate the prompt feedback.
