### ISSUE TITLE
Handle IDENTITY columns

### ISSUE THREAD

**Issue by dariemp** [awslabs/amazon-redshift-utils#94]
The insert-select part of the migration in ColumnEncodingUtility does not handle columns of type IDENTITY, since SELECT gets all the columns but INSERT refuses to insert any columns of the type IDENTITY.

**Comment by coryodaniel** [comment]
I have experienced the same issue on master... it looks like the regexp isn't matching. An example column definition that isn't matching is:

```
"id" bigint default "identity"(204375, 0, ('1,1'::character varying)::text) NOT NULL encode lzo
```

**Comment by IanMeyers** [comment]
Hi - sorry we missed this one - looking into it.

**Comment by IanMeyers** [comment]
Can you please retest with version .9.2.2 from https://github.com/awslabs/amazon-redshift-utils/commit/54cc0fa77038e74303d1627a931d867bbe9a5bba? This should now support multiple different datatypes.

**Comment by IanMeyers** [comment]
Closing now as this should be OK - can you please re-open if there's still an issue?
