### ISSUE TITLE
getting list of tables by deleted-pct in AnalyzeVacuumUtility uses deprecated column and doesn't seem to work anymore

### ISSUE THREAD

**Issue by cswilliams** [awslabs/amazon-redshift-utils#97]
Hi,

The query used in https://github.com/awslabs/amazon-redshift-utils/blob/master/src/AnalyzeVacuumUtility/analyze-vacuum-schema.py#L251 is using svv_table_info.empty which Amazon says is deprecated (http://docs.aws.amazon.com/redshift/latest/dg/r_SVV_TABLE_INFO.html).  From my testing, the column is always 0 for every table, even tables with a lot of deleted space to be reclaimed.  So I believe this no longer works correctly. I opened a ticket on the redshift forum and they provided a new query:
select ae.event_time::date, qr.label, count(distinct ae.query) as query_count, count(*) as alert_count, max(ae.query) as sample_query   from stl_alert_event_log ae, svl_query_report qr, stl_query sq where substring(ae.event, 1,30) = 'Scanned a large number of dele' and ae.event_time::date between (getdate()-7)::date and getdate()::date and lower(sq.querytxt) not like 'padb_fetch_sample:%' and ae.query = qr.query and ae.segment = qr.segment and ae.step = qr.step and ae.slice = qr.slice and ae.query = sq.query group by ae.event_time::date, qr.label order by ae.event_time::date desc, 4 desc , 3 desc;

Anyhow, just thought I would report this issue.  This new query isn't quite the same as before, so probably requires changing the script a bit.

Best,
Chris

**Comment by someboredkiddo** [comment]
Are there any plans to update the utility or a new script we should use to capture tables with a large number of deleted rows in need of vacuuming?

**Comment by IanMeyers** [comment]
Unfortunately that amended script is query based as opposed to object based, and so will need some rework. I'm checking into what we can do to address this now.

Thx!

**Comment by IanMeyers** [comment]
I've removed the references to the `empty` column now, which as they were in an `or` statement wasn't going to create an issue, but still is deprecated so this is a good thing to do. https://github.com/awslabs/amazon-redshift-utils/commit/41423bfa627970c62e3d89ae3cc8be5a555895e2

**Comment by timjell** [comment]
Closing issue as fixed by the above commit.
